# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_hydrant_attribute.ui'
#
# Created: Tue Nov 27 17:09:22 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HydrantAttribute(object):
    def setupUi(self, HydrantAttribute):
        HydrantAttribute.setObjectName(_fromUtf8("HydrantAttribute"))
        HydrantAttribute.setWindowModality(QtCore.Qt.NonModal)
        HydrantAttribute.resize(801, 895)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AcadEref"))
        font.setPointSize(12)
        HydrantAttribute.setFont(font)
        HydrantAttribute.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        HydrantAttribute.setToolTip(_fromUtf8(""))
        HydrantAttribute.setModal(False)
        self.tabWidget = QtGui.QTabWidget(HydrantAttribute)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 841))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_hydrant_turn = QtGui.QLabel(self.tab_4)
        self.label_hydrant_turn.setGeometry(QtCore.QRect(268, 140, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_turn.setFont(font)
        self.label_hydrant_turn.setFrameShape(QtGui.QFrame.Box)
        self.label_hydrant_turn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_turn.setObjectName(_fromUtf8("label_hydrant_turn"))
        self.lineEdit_admin_unit = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_admin_unit.setGeometry(QtCore.QRect(124, 380, 384, 32))
        self.lineEdit_admin_unit.setMaxLength(30)
        self.lineEdit_admin_unit.setObjectName(_fromUtf8("lineEdit_admin_unit"))
        self.comboBox_hydrant_status = QtGui.QComboBox(self.tab_4)
        self.comboBox_hydrant_status.setGeometry(QtCore.QRect(372, 60, 136, 32))
        self.comboBox_hydrant_status.setObjectName(_fromUtf8("comboBox_hydrant_status"))
        self.comboBox_hydrant_status.addItem(_fromUtf8(""))
        self.comboBox_hydrant_status.addItem(_fromUtf8(""))
        self.label_bury_loc = QtGui.QLabel(self.tab_4)
        self.label_bury_loc.setGeometry(QtCore.QRect(20, 260, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bury_loc.setFont(font)
        self.label_bury_loc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bury_loc.setObjectName(_fromUtf8("label_bury_loc"))
        self.label_hydrant_status = QtGui.QLabel(self.tab_4)
        self.label_hydrant_status.setGeometry(QtCore.QRect(268, 60, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_status.setFont(font)
        self.label_hydrant_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_status.setObjectName(_fromUtf8("label_hydrant_status"))
        self.lineEdit_coord_67y = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_67y.setGeometry(QtCore.QRect(620, 676, 136, 32))
        self.lineEdit_coord_67y.setObjectName(_fromUtf8("lineEdit_coord_67y"))
        self.label_coord_97y = QtGui.QLabel(self.tab_4)
        self.label_coord_97y.setGeometry(QtCore.QRect(460, 716, 152, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_97y.setFont(font)
        self.label_coord_97y.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_97y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_97y.setObjectName(_fromUtf8("label_coord_97y"))
        self.label_coord_67y = QtGui.QLabel(self.tab_4)
        self.label_coord_67y.setGeometry(QtCore.QRect(460, 676, 152, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_67y.setFont(font)
        self.label_coord_67y.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_67y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_67y.setObjectName(_fromUtf8("label_coord_67y"))
        self.comboBox_hydrant_type = QtGui.QComboBox(self.tab_4)
        self.comboBox_hydrant_type.setGeometry(QtCore.QRect(492, 20, 264, 32))
        self.comboBox_hydrant_type.setObjectName(_fromUtf8("comboBox_hydrant_type"))
        self.comboBox_hydrant_type.addItem(_fromUtf8(""))
        self.comboBox_hydrant_type.addItem(_fromUtf8(""))
        self.comboBox_hydrant_type.addItem(_fromUtf8(""))
        self.comboBox_hydrant_type.addItem(_fromUtf8(""))
        self.comboBox_hydrant_type.addItem(_fromUtf8(""))
        self.comboBox_hydrant_type.addItem(_fromUtf8(""))
        self.plainTextEdit_maint_rec = QtGui.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_maint_rec.setGeometry(QtCore.QRect(40, 630, 31, 31))
        self.plainTextEdit_maint_rec.setObjectName(_fromUtf8("plainTextEdit_maint_rec"))
        self.label_const_unit = QtGui.QLabel(self.tab_4)
        self.label_const_unit.setGeometry(QtCore.QRect(20, 340, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_const_unit.setFont(font)
        self.label_const_unit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_const_unit.setObjectName(_fromUtf8("label_const_unit"))
        self.label_hydrant_pd = QtGui.QLabel(self.tab_4)
        self.label_hydrant_pd.setGeometry(QtCore.QRect(253, 100, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_pd.setFont(font)
        self.label_hydrant_pd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_pd.setObjectName(_fromUtf8("label_hydrant_pd"))
        self.comboBox_unific_id = QtGui.QComboBox(self.tab_4)
        self.comboBox_unific_id.setGeometry(QtCore.QRect(370, 20, 21, 32))
        self.comboBox_unific_id.setObjectName(_fromUtf8("comboBox_unific_id"))
        self.lineEdit_cvalve_turn = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_cvalve_turn.setGeometry(QtCore.QRect(124, 220, 131, 32))
        self.lineEdit_cvalve_turn.setObjectName(_fromUtf8("lineEdit_cvalve_turn"))
        self.label_cpipe_size = QtGui.QLabel(self.tab_4)
        self.label_cpipe_size.setGeometry(QtCore.QRect(516, 140, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cpipe_size.setFont(font)
        self.label_cpipe_size.setFrameShape(QtGui.QFrame.Box)
        self.label_cpipe_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cpipe_size.setObjectName(_fromUtf8("label_cpipe_size"))
        self.lineEdit_hydrant_pd = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_hydrant_pd.setGeometry(QtCore.QRect(372, 100, 136, 32))
        self.lineEdit_hydrant_pd.setMaxLength(20)
        self.lineEdit_hydrant_pd.setObjectName(_fromUtf8("lineEdit_hydrant_pd"))
        self.lineEdit_hydrant_model = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_hydrant_model.setGeometry(QtCore.QRect(124, 100, 131, 32))
        self.lineEdit_hydrant_model.setMaxLength(20)
        self.lineEdit_hydrant_model.setObjectName(_fromUtf8("lineEdit_hydrant_model"))
        self.pushButtonOK = QtGui.QPushButton(self.tab_4)
        self.pushButtonOK.setGeometry(QtCore.QRect(640, 760, 136, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.lineEdit_firebureau_id = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_firebureau_id.setGeometry(QtCore.QRect(620, 100, 136, 32))
        self.lineEdit_firebureau_id.setMaxLength(20)
        self.lineEdit_firebureau_id.setObjectName(_fromUtf8("lineEdit_firebureau_id"))
        self.lineEdit_coord_97z = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_97z.setGeometry(QtCore.QRect(284, 636, 136, 32))
        self.lineEdit_coord_97z.setInputMask(_fromUtf8(""))
        self.lineEdit_coord_97z.setText(_fromUtf8(""))
        self.lineEdit_coord_97z.setObjectName(_fromUtf8("lineEdit_coord_97z"))
        self.lineEdit_proj_name = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_proj_name.setGeometry(QtCore.QRect(124, 300, 632, 32))
        self.lineEdit_proj_name.setMaxLength(50)
        self.lineEdit_proj_name.setObjectName(_fromUtf8("lineEdit_proj_name"))
        self.comboBox_cvalve_sw = QtGui.QComboBox(self.tab_4)
        self.comboBox_cvalve_sw.setGeometry(QtCore.QRect(620, 180, 136, 32))
        self.comboBox_cvalve_sw.setObjectName(_fromUtf8("comboBox_cvalve_sw"))
        self.comboBox_cvalve_sw.addItem(_fromUtf8(""))
        self.comboBox_cvalve_sw.addItem(_fromUtf8(""))
        self.lineEdit_cpipe_size = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_cpipe_size.setGeometry(QtCore.QRect(620, 140, 136, 32))
        self.lineEdit_cpipe_size.setInputMask(_fromUtf8(""))
        self.lineEdit_cpipe_size.setMaxLength(4)
        self.lineEdit_cpipe_size.setObjectName(_fromUtf8("lineEdit_cpipe_size"))
        self.label_hydrant_mode = QtGui.QLabel(self.tab_4)
        self.label_hydrant_mode.setGeometry(QtCore.QRect(516, 380, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_mode.setFont(font)
        self.label_hydrant_mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_mode.setObjectName(_fromUtf8("label_hydrant_mode"))
        self.label_outlet_size = QtGui.QLabel(self.tab_4)
        self.label_outlet_size.setGeometry(QtCore.QRect(20, 180, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_outlet_size.setFont(font)
        self.label_outlet_size.setFrameShape(QtGui.QFrame.Box)
        self.label_outlet_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_outlet_size.setObjectName(_fromUtf8("label_outlet_size"))
        self.lineEdit_coord_97y = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_97y.setGeometry(QtCore.QRect(620, 716, 136, 32))
        self.lineEdit_coord_97y.setObjectName(_fromUtf8("lineEdit_coord_97y"))
        self.label_hydrant_size = QtGui.QLabel(self.tab_4)
        self.label_hydrant_size.setGeometry(QtCore.QRect(20, 140, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_size.setFont(font)
        self.label_hydrant_size.setFrameShape(QtGui.QFrame.Box)
        self.label_hydrant_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_size.setObjectName(_fromUtf8("label_hydrant_size"))
        self.label_hydrant_sw = QtGui.QLabel(self.tab_4)
        self.label_hydrant_sw.setGeometry(QtCore.QRect(516, 60, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_sw.setFont(font)
        self.label_hydrant_sw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_sw.setObjectName(_fromUtf8("label_hydrant_sw"))
        self.label_maint_date = QtGui.QLabel(self.tab_4)
        self.label_maint_date.setGeometry(QtCore.QRect(20, 470, 96, 64))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_maint_date.setFont(font)
        self.label_maint_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_maint_date.setObjectName(_fromUtf8("label_maint_date"))
        self.label_remark = QtGui.QLabel(self.tab_4)
        self.label_remark.setGeometry(QtCore.QRect(20, 596, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_remark.setFont(font)
        self.label_remark.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_remark.setObjectName(_fromUtf8("label_remark"))
        self.lineEdit_pressure = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_pressure.setGeometry(QtCore.QRect(620, 340, 136, 32))
        self.lineEdit_pressure.setInputMask(_fromUtf8(""))
        self.lineEdit_pressure.setText(_fromUtf8(""))
        self.lineEdit_pressure.setObjectName(_fromUtf8("lineEdit_pressure"))
        self.lineEdit_bury_date = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_bury_date.setGeometry(QtCore.QRect(620, 220, 136, 32))
        self.lineEdit_bury_date.setMaxLength(8)
        self.lineEdit_bury_date.setObjectName(_fromUtf8("lineEdit_bury_date"))
        self.lineEdit_bury_loc = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_bury_loc.setGeometry(QtCore.QRect(124, 260, 632, 32))
        self.lineEdit_bury_loc.setMaxLength(60)
        self.lineEdit_bury_loc.setObjectName(_fromUtf8("lineEdit_bury_loc"))
        self.lineEdit_const_unit = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_const_unit.setGeometry(QtCore.QRect(124, 340, 384, 32))
        self.lineEdit_const_unit.setMaxLength(30)
        self.lineEdit_const_unit.setObjectName(_fromUtf8("lineEdit_const_unit"))
        self.label_coord_97x = QtGui.QLabel(self.tab_4)
        self.label_coord_97x.setGeometry(QtCore.QRect(124, 716, 152, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_97x.setFont(font)
        self.label_coord_97x.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_97x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_97x.setObjectName(_fromUtf8("label_coord_97x"))
        self.label_firebureau_id = QtGui.QLabel(self.tab_4)
        self.label_firebureau_id.setGeometry(QtCore.QRect(516, 100, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_firebureau_id.setFont(font)
        self.label_firebureau_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_firebureau_id.setObjectName(_fromUtf8("label_firebureau_id"))
        self.lineEdit_cvalve_model = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_cvalve_model.setGeometry(QtCore.QRect(372, 180, 136, 32))
        self.lineEdit_cvalve_model.setMaxLength(20)
        self.lineEdit_cvalve_model.setObjectName(_fromUtf8("lineEdit_cvalve_model"))
        self.label_bury_depth = QtGui.QLabel(self.tab_4)
        self.label_bury_depth.setGeometry(QtCore.QRect(268, 220, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bury_depth.setFont(font)
        self.label_bury_depth.setFrameShape(QtGui.QFrame.Box)
        self.label_bury_depth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bury_depth.setObjectName(_fromUtf8("label_bury_depth"))
        self.label_admin_unit = QtGui.QLabel(self.tab_4)
        self.label_admin_unit.setGeometry(QtCore.QRect(20, 380, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_admin_unit.setFont(font)
        self.label_admin_unit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_admin_unit.setObjectName(_fromUtf8("label_admin_unit"))
        self.lineEdit_hydrant_turn = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_hydrant_turn.setGeometry(QtCore.QRect(372, 140, 136, 32))
        self.lineEdit_hydrant_turn.setObjectName(_fromUtf8("lineEdit_hydrant_turn"))
        self.label_cvalve_model = QtGui.QLabel(self.tab_4)
        self.label_cvalve_model.setGeometry(QtCore.QRect(268, 180, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cvalve_model.setFont(font)
        self.label_cvalve_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cvalve_model.setObjectName(_fromUtf8("label_cvalve_model"))
        self.label_proj_name = QtGui.QLabel(self.tab_4)
        self.label_proj_name.setGeometry(QtCore.QRect(20, 300, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_proj_name.setFont(font)
        self.label_proj_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_proj_name.setObjectName(_fromUtf8("label_proj_name"))
        self.label_coord_67x = QtGui.QLabel(self.tab_4)
        self.label_coord_67x.setGeometry(QtCore.QRect(124, 676, 152, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_67x.setFont(font)
        self.label_coord_67x.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_67x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_67x.setObjectName(_fromUtf8("label_coord_67x"))
        self.comboBox_hydrant_sw = QtGui.QComboBox(self.tab_4)
        self.comboBox_hydrant_sw.setGeometry(QtCore.QRect(620, 60, 136, 32))
        self.comboBox_hydrant_sw.setObjectName(_fromUtf8("comboBox_hydrant_sw"))
        self.comboBox_hydrant_sw.addItem(_fromUtf8(""))
        self.comboBox_hydrant_sw.addItem(_fromUtf8(""))
        self.label_pressure = QtGui.QLabel(self.tab_4)
        self.label_pressure.setGeometry(QtCore.QRect(516, 340, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_pressure.setFont(font)
        self.label_pressure.setFrameShape(QtGui.QFrame.Box)
        self.label_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pressure.setObjectName(_fromUtf8("label_pressure"))
        self.label_cvalve_sw = QtGui.QLabel(self.tab_4)
        self.label_cvalve_sw.setGeometry(QtCore.QRect(516, 180, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cvalve_sw.setFont(font)
        self.label_cvalve_sw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cvalve_sw.setObjectName(_fromUtf8("label_cvalve_sw"))
        self.label_coord_97z = QtGui.QLabel(self.tab_4)
        self.label_coord_97z.setGeometry(QtCore.QRect(124, 636, 152, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_97z.setFont(font)
        self.label_coord_97z.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_97z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_97z.setObjectName(_fromUtf8("label_coord_97z"))
        self.lineEdit_coord_97x = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_97x.setGeometry(QtCore.QRect(284, 716, 136, 32))
        self.lineEdit_coord_97x.setObjectName(_fromUtf8("lineEdit_coord_97x"))
        self.lineEdit_hydrant_size = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_hydrant_size.setGeometry(QtCore.QRect(124, 140, 131, 32))
        self.lineEdit_hydrant_size.setInputMask(_fromUtf8(""))
        self.lineEdit_hydrant_size.setMaxLength(4)
        self.lineEdit_hydrant_size.setObjectName(_fromUtf8("lineEdit_hydrant_size"))
        self.label_unific_id = QtGui.QLabel(self.tab_4)
        self.label_unific_id.setGeometry(QtCore.QRect(20, 20, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_unific_id.setFont(font)
        self.label_unific_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_unific_id.setObjectName(_fromUtf8("label_unific_id"))
        self.lineEdit_remark = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_remark.setGeometry(QtCore.QRect(124, 596, 632, 32))
        self.lineEdit_remark.setMaxLength(50)
        self.lineEdit_remark.setObjectName(_fromUtf8("lineEdit_remark"))
        self.comboBox_hydrant_mode = QtGui.QComboBox(self.tab_4)
        self.comboBox_hydrant_mode.setGeometry(QtCore.QRect(620, 380, 136, 32))
        self.comboBox_hydrant_mode.setObjectName(_fromUtf8("comboBox_hydrant_mode"))
        self.comboBox_hydrant_mode.addItem(_fromUtf8(""))
        self.comboBox_hydrant_mode.addItem(_fromUtf8(""))
        self.comboBox_hydrant_mode.addItem(_fromUtf8(""))
        self.label_cvalve_turn = QtGui.QLabel(self.tab_4)
        self.label_cvalve_turn.setGeometry(QtCore.QRect(20, 220, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_cvalve_turn.setFont(font)
        self.label_cvalve_turn.setFrameShape(QtGui.QFrame.Box)
        self.label_cvalve_turn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cvalve_turn.setObjectName(_fromUtf8("label_cvalve_turn"))
        self.lineEdit_hydrant_id = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_hydrant_id.setGeometry(QtCore.QRect(124, 60, 131, 32))
        self.lineEdit_hydrant_id.setMaxLength(15)
        self.lineEdit_hydrant_id.setObjectName(_fromUtf8("lineEdit_hydrant_id"))
        self.label_hydrant_type = QtGui.QLabel(self.tab_4)
        self.label_hydrant_type.setGeometry(QtCore.QRect(388, 20, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_type.setFont(font)
        self.label_hydrant_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_type.setObjectName(_fromUtf8("label_hydrant_type"))
        self.label_hydrant_id = QtGui.QLabel(self.tab_4)
        self.label_hydrant_id.setGeometry(QtCore.QRect(20, 60, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_id.setFont(font)
        self.label_hydrant_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_id.setObjectName(_fromUtf8("label_hydrant_id"))
        self.lineEdit_outlet_size = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_outlet_size.setGeometry(QtCore.QRect(124, 180, 131, 32))
        self.lineEdit_outlet_size.setInputMask(_fromUtf8(""))
        self.lineEdit_outlet_size.setMaxLength(4)
        self.lineEdit_outlet_size.setObjectName(_fromUtf8("lineEdit_outlet_size"))
        self.plainTextEdit_maint_date = QtGui.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_maint_date.setGeometry(QtCore.QRect(40, 660, 31, 31))
        self.plainTextEdit_maint_date.setObjectName(_fromUtf8("plainTextEdit_maint_date"))
        self.lineEdit_coord_67x = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_67x.setGeometry(QtCore.QRect(284, 676, 136, 32))
        self.lineEdit_coord_67x.setObjectName(_fromUtf8("lineEdit_coord_67x"))
        self.label_bury_date = QtGui.QLabel(self.tab_4)
        self.label_bury_date.setGeometry(QtCore.QRect(516, 220, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bury_date.setFont(font)
        self.label_bury_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bury_date.setObjectName(_fromUtf8("label_bury_date"))
        self.label_hydrant_model = QtGui.QLabel(self.tab_4)
        self.label_hydrant_model.setGeometry(QtCore.QRect(20, 100, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hydrant_model.setFont(font)
        self.label_hydrant_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hydrant_model.setObjectName(_fromUtf8("label_hydrant_model"))
        self.lineEdit_bury_depth = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_bury_depth.setGeometry(QtCore.QRect(372, 220, 136, 32))
        self.lineEdit_bury_depth.setInputMask(_fromUtf8(""))
        self.lineEdit_bury_depth.setText(_fromUtf8(""))
        self.lineEdit_bury_depth.setObjectName(_fromUtf8("lineEdit_bury_depth"))
        self.lineEdit_unific_id = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_unific_id.setGeometry(QtCore.QRect(124, 20, 241, 32))
        self.lineEdit_unific_id.setMaxLength(22)
        self.lineEdit_unific_id.setObjectName(_fromUtf8("lineEdit_unific_id"))
        self.listWidget_maint_date = QtGui.QListWidget(self.tab_4)
        self.listWidget_maint_date.setGeometry(QtCore.QRect(124, 420, 631, 161))
        self.listWidget_maint_date.setObjectName(_fromUtf8("listWidget_maint_date"))
        self.btUID = QtGui.QPushButton(self.tab_4)
        self.btUID.setGeometry(QtCore.QRect(510, 760, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btUID.setFont(font)
        self.btUID.setObjectName(_fromUtf8("btUID"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(80, 40, 621, 131))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lbl_pin1 = QtGui.QLabel(self.groupBox)
        self.lbl_pin1.setGeometry(QtCore.QRect(20, 30, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_pin1.setFont(font)
        self.lbl_pin1.setObjectName(_fromUtf8("lbl_pin1"))
        self.lbl_pin2 = QtGui.QLabel(self.groupBox)
        self.lbl_pin2.setGeometry(QtCore.QRect(20, 60, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_pin2.setFont(font)
        self.lbl_pin2.setObjectName(_fromUtf8("lbl_pin2"))
        self.lbl_pin3 = QtGui.QLabel(self.groupBox)
        self.lbl_pin3.setGeometry(QtCore.QRect(20, 90, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_pin3.setFont(font)
        self.lbl_pin3.setObjectName(_fromUtf8("lbl_pin3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 180, 621, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.teP1disc = QtGui.QTextEdit(self.groupBox_2)
        self.teP1disc.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.teP1disc.setFont(font)
        self.teP1disc.setFrameShape(QtGui.QFrame.Panel)
        self.teP1disc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1disc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1disc.setObjectName(_fromUtf8("teP1disc"))
        self.cbP1pos = QtGui.QComboBox(self.groupBox_2)
        self.cbP1pos.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbP1pos.setFont(font)
        self.cbP1pos.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cbP1pos.setObjectName(_fromUtf8("cbP1pos"))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.setItemText(0, _fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.teP1dis = QtGui.QTextEdit(self.groupBox_2)
        self.teP1dis.setGeometry(QtCore.QRect(470, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP1dis.setFont(font)
        self.teP1dis.setFrameShape(QtGui.QFrame.Panel)
        self.teP1dis.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1dis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1dis.setObjectName(_fromUtf8("teP1dis"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(560, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.teP1x = QtGui.QTextEdit(self.groupBox_2)
        self.teP1x.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP1x.setFont(font)
        self.teP1x.setFrameShape(QtGui.QFrame.Panel)
        self.teP1x.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1x.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1x.setObjectName(_fromUtf8("teP1x"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(250, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.teP1y = QtGui.QTextEdit(self.groupBox_2)
        self.teP1y.setGeometry(QtCore.QRect(270, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP1y.setFont(font)
        self.teP1y.setFrameShape(QtGui.QFrame.Panel)
        self.teP1y.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1y.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1y.setObjectName(_fromUtf8("teP1y"))
        self.btP1xy = QtGui.QPushButton(self.groupBox_2)
        self.btP1xy.setGeometry(QtCore.QRect(470, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.btP1xy.setFont(font)
        self.btP1xy.setObjectName(_fromUtf8("btP1xy"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(80, 300, 621, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.teP2disc = QtGui.QTextEdit(self.groupBox_3)
        self.teP2disc.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2disc.setFont(font)
        self.teP2disc.setFrameShape(QtGui.QFrame.Panel)
        self.teP2disc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2disc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2disc.setObjectName(_fromUtf8("teP2disc"))
        self.cbP2pos = QtGui.QComboBox(self.groupBox_3)
        self.cbP2pos.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbP2pos.setFont(font)
        self.cbP2pos.setObjectName(_fromUtf8("cbP2pos"))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.setItemText(0, _fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.teP2dis = QtGui.QTextEdit(self.groupBox_3)
        self.teP2dis.setGeometry(QtCore.QRect(470, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2dis.setFont(font)
        self.teP2dis.setFrameShape(QtGui.QFrame.Panel)
        self.teP2dis.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2dis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2dis.setObjectName(_fromUtf8("teP2dis"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(560, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.teP2x = QtGui.QTextEdit(self.groupBox_3)
        self.teP2x.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2x.setFont(font)
        self.teP2x.setFrameShape(QtGui.QFrame.Panel)
        self.teP2x.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2x.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2x.setObjectName(_fromUtf8("teP2x"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(250, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.teP2y = QtGui.QTextEdit(self.groupBox_3)
        self.teP2y.setGeometry(QtCore.QRect(270, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2y.setFont(font)
        self.teP2y.setFrameShape(QtGui.QFrame.Panel)
        self.teP2y.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2y.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2y.setObjectName(_fromUtf8("teP2y"))
        self.btP2xy = QtGui.QPushButton(self.groupBox_3)
        self.btP2xy.setGeometry(QtCore.QRect(470, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.btP2xy.setFont(font)
        self.btP2xy.setObjectName(_fromUtf8("btP2xy"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(80, 420, 621, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.teP3disc = QtGui.QTextEdit(self.groupBox_4)
        self.teP3disc.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.teP3disc.setFont(font)
        self.teP3disc.setFrameShape(QtGui.QFrame.Panel)
        self.teP3disc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3disc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3disc.setObjectName(_fromUtf8("teP3disc"))
        self.cbP3pos = QtGui.QComboBox(self.groupBox_4)
        self.cbP3pos.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbP3pos.setFont(font)
        self.cbP3pos.setObjectName(_fromUtf8("cbP3pos"))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.setItemText(0, _fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.teP3dis = QtGui.QTextEdit(self.groupBox_4)
        self.teP3dis.setGeometry(QtCore.QRect(470, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP3dis.setFont(font)
        self.teP3dis.setFrameShape(QtGui.QFrame.Panel)
        self.teP3dis.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3dis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3dis.setObjectName(_fromUtf8("teP3dis"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(560, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.teP3x = QtGui.QTextEdit(self.groupBox_4)
        self.teP3x.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP3x.setFont(font)
        self.teP3x.setFrameShape(QtGui.QFrame.Panel)
        self.teP3x.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3x.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3x.setObjectName(_fromUtf8("teP3x"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(250, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.teP3y = QtGui.QTextEdit(self.groupBox_4)
        self.teP3y.setGeometry(QtCore.QRect(270, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP3y.setFont(font)
        self.teP3y.setFrameShape(QtGui.QFrame.Panel)
        self.teP3y.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3y.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3y.setObjectName(_fromUtf8("teP3y"))
        self.btP3xy = QtGui.QPushButton(self.groupBox_4)
        self.btP3xy.setGeometry(QtCore.QRect(470, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.btP3xy.setFont(font)
        self.btP3xy.setObjectName(_fromUtf8("btP3xy"))
        self.pushButtonOK_pin = QtGui.QPushButton(self.tab)
        self.pushButtonOK_pin.setGeometry(QtCore.QRect(320, 550, 136, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOK_pin.setFont(font)
        self.pushButtonOK_pin.setObjectName(_fromUtf8("pushButtonOK_pin"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gvPhoto = QtGui.QGraphicsView(self.tab_3)
        self.gvPhoto.setGeometry(QtCore.QRect(10, 10, 751, 661))
        self.gvPhoto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvPhoto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvPhoto.setInteractive(False)
        self.gvPhoto.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.gvPhoto.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.gvPhoto.setObjectName(_fromUtf8("gvPhoto"))
        self.btPrephoto = QtGui.QPushButton(self.tab_3)
        self.btPrephoto.setGeometry(QtCore.QRect(490, 690, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btPrephoto.setFont(font)
        self.btPrephoto.setObjectName(_fromUtf8("btPrephoto"))
        self.btNextphoto = QtGui.QPushButton(self.tab_3)
        self.btNextphoto.setGeometry(QtCore.QRect(570, 690, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btNextphoto.setFont(font)
        self.btNextphoto.setObjectName(_fromUtf8("btNextphoto"))
        self.btOpenphoto = QtGui.QPushButton(self.tab_3)
        self.btOpenphoto.setGeometry(QtCore.QRect(650, 690, 91, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btOpenphoto.setFont(font)
        self.btOpenphoto.setObjectName(_fromUtf8("btOpenphoto"))
        self.lbl_photoname = QtGui.QLabel(self.tab_3)
        self.lbl_photoname.setGeometry(QtCore.QRect(10, 680, 361, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_photoname.setFont(font)
        self.lbl_photoname.setObjectName(_fromUtf8("lbl_photoname"))
        self.pushButton_open_folder = QtGui.QPushButton(self.tab_3)
        self.pushButton_open_folder.setGeometry(QtCore.QRect(20, 720, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_open_folder.setFont(font)
        self.pushButton_open_folder.setObjectName(_fromUtf8("pushButton_open_folder"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.teModel = QtGui.QTextEdit(self.tab_2)
        self.teModel.setGeometry(QtCore.QRect(170, 40, 161, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teModel.setFont(font)
        self.teModel.setFrameShape(QtGui.QFrame.Panel)
        self.teModel.setFrameShadow(QtGui.QFrame.Sunken)
        self.teModel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teModel.setObjectName(_fromUtf8("teModel"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(60, 280, 671, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.teWork03 = QtGui.QTextEdit(self.groupBox_5)
        self.teWork03.setGeometry(QtCore.QRect(349, 107, 311, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teWork03.setFont(font)
        self.teWork03.setFrameShape(QtGui.QFrame.Panel)
        self.teWork03.setFrameShadow(QtGui.QFrame.Sunken)
        self.teWork03.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teWork03.setObjectName(_fromUtf8("teWork03"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(260, 30, 81, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_36 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_3.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_3.addWidget(self.label_37)
        self.label_38 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_3.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_3.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_3.addWidget(self.label_40)
        self.label_41 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_3.addWidget(self.label_41)
        self.teWork05 = QtGui.QTextEdit(self.groupBox_5)
        self.teWork05.setGeometry(QtCore.QRect(349, 182, 311, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teWork05.setFont(font)
        self.teWork05.setFrameShape(QtGui.QFrame.Panel)
        self.teWork05.setFrameShadow(QtGui.QFrame.Sunken)
        self.teWork05.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teWork05.setObjectName(_fromUtf8("teWork05"))
        self.teWork06 = QtGui.QTextEdit(self.groupBox_5)
        self.teWork06.setGeometry(QtCore.QRect(349, 220, 311, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teWork06.setFont(font)
        self.teWork06.setFrameShape(QtGui.QFrame.Panel)
        self.teWork06.setFrameShadow(QtGui.QFrame.Sunken)
        self.teWork06.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teWork06.setObjectName(_fromUtf8("teWork06"))
        self.teDate01 = QtGui.QTextEdit(self.groupBox_5)
        self.teDate01.setGeometry(QtCore.QRect(120, 28, 101, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teDate01.setFont(font)
        self.teDate01.setFrameShape(QtGui.QFrame.Panel)
        self.teDate01.setFrameShadow(QtGui.QFrame.Sunken)
        self.teDate01.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teDate01.setObjectName(_fromUtf8("teDate01"))
        self.teWork01 = QtGui.QTextEdit(self.groupBox_5)
        self.teWork01.setGeometry(QtCore.QRect(349, 32, 311, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teWork01.setFont(font)
        self.teWork01.setFrameShape(QtGui.QFrame.Panel)
        self.teWork01.setFrameShadow(QtGui.QFrame.Sunken)
        self.teWork01.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teWork01.setObjectName(_fromUtf8("teWork01"))
        self.teDate02 = QtGui.QTextEdit(self.groupBox_5)
        self.teDate02.setGeometry(QtCore.QRect(120, 66, 101, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teDate02.setFont(font)
        self.teDate02.setFrameShape(QtGui.QFrame.Panel)
        self.teDate02.setFrameShadow(QtGui.QFrame.Sunken)
        self.teDate02.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teDate02.setObjectName(_fromUtf8("teDate02"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(9, 30, 101, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        self.layoutWidget_3.setFont(font)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_26 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_42 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_4.addWidget(self.label_42)
        self.label_43 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_4.addWidget(self.label_43)
        self.label_44 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_4.addWidget(self.label_44)
        self.label_45 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.verticalLayout_4.addWidget(self.label_45)
        self.label_46 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.verticalLayout_4.addWidget(self.label_46)
        self.teDate06 = QtGui.QTextEdit(self.groupBox_5)
        self.teDate06.setGeometry(QtCore.QRect(120, 216, 101, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teDate06.setFont(font)
        self.teDate06.setFrameShape(QtGui.QFrame.Panel)
        self.teDate06.setFrameShadow(QtGui.QFrame.Sunken)
        self.teDate06.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teDate06.setObjectName(_fromUtf8("teDate06"))
        self.teWork02 = QtGui.QTextEdit(self.groupBox_5)
        self.teWork02.setGeometry(QtCore.QRect(349, 70, 311, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teWork02.setFont(font)
        self.teWork02.setFrameShape(QtGui.QFrame.Panel)
        self.teWork02.setFrameShadow(QtGui.QFrame.Sunken)
        self.teWork02.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teWork02.setObjectName(_fromUtf8("teWork02"))
        self.teDate03 = QtGui.QTextEdit(self.groupBox_5)
        self.teDate03.setGeometry(QtCore.QRect(120, 104, 101, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teDate03.setFont(font)
        self.teDate03.setFrameShape(QtGui.QFrame.Panel)
        self.teDate03.setFrameShadow(QtGui.QFrame.Sunken)
        self.teDate03.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teDate03.setObjectName(_fromUtf8("teDate03"))
        self.teWork04 = QtGui.QTextEdit(self.groupBox_5)
        self.teWork04.setGeometry(QtCore.QRect(349, 145, 311, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teWork04.setFont(font)
        self.teWork04.setFrameShape(QtGui.QFrame.Panel)
        self.teWork04.setFrameShadow(QtGui.QFrame.Sunken)
        self.teWork04.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teWork04.setObjectName(_fromUtf8("teWork04"))
        self.teDate04 = QtGui.QTextEdit(self.groupBox_5)
        self.teDate04.setGeometry(QtCore.QRect(120, 141, 101, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teDate04.setFont(font)
        self.teDate04.setFrameShape(QtGui.QFrame.Panel)
        self.teDate04.setFrameShadow(QtGui.QFrame.Sunken)
        self.teDate04.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teDate04.setObjectName(_fromUtf8("teDate04"))
        self.teDate05 = QtGui.QTextEdit(self.groupBox_5)
        self.teDate05.setGeometry(QtCore.QRect(120, 181, 101, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teDate05.setFont(font)
        self.teDate05.setFrameShape(QtGui.QFrame.Panel)
        self.teDate05.setFrameShadow(QtGui.QFrame.Sunken)
        self.teDate05.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teDate05.setObjectName(_fromUtf8("teDate05"))
        self.dte01 = QtGui.QDateEdit(self.groupBox_5)
        self.dte01.setGeometry(QtCore.QRect(221, 28, 17, 33))
        self.dte01.setCalendarPopup(True)
        self.dte01.setObjectName(_fromUtf8("dte01"))
        self.dte02 = QtGui.QDateEdit(self.groupBox_5)
        self.dte02.setGeometry(QtCore.QRect(221, 66, 17, 33))
        self.dte02.setCalendarPopup(True)
        self.dte02.setObjectName(_fromUtf8("dte02"))
        self.dte03 = QtGui.QDateEdit(self.groupBox_5)
        self.dte03.setGeometry(QtCore.QRect(221, 104, 17, 33))
        self.dte03.setCalendarPopup(True)
        self.dte03.setObjectName(_fromUtf8("dte03"))
        self.dte04 = QtGui.QDateEdit(self.groupBox_5)
        self.dte04.setGeometry(QtCore.QRect(221, 141, 17, 33))
        self.dte04.setCalendarPopup(True)
        self.dte04.setObjectName(_fromUtf8("dte04"))
        self.dte05 = QtGui.QDateEdit(self.groupBox_5)
        self.dte05.setGeometry(QtCore.QRect(221, 181, 17, 33))
        self.dte05.setCalendarPopup(True)
        self.dte05.setObjectName(_fromUtf8("dte05"))
        self.dte06 = QtGui.QDateEdit(self.groupBox_5)
        self.dte06.setGeometry(QtCore.QRect(221, 216, 17, 33))
        self.dte06.setCalendarPopup(True)
        self.dte06.setObjectName(_fromUtf8("dte06"))
        self.teBloc = QtGui.QTextEdit(self.tab_2)
        self.teBloc.setGeometry(QtCore.QRect(500, 42, 211, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teBloc.setFont(font)
        self.teBloc.setFrameShape(QtGui.QFrame.Panel)
        self.teBloc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teBloc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teBloc.setObjectName(_fromUtf8("teBloc"))
        self.tePd = QtGui.QTextEdit(self.tab_2)
        self.tePd.setGeometry(QtCore.QRect(170, 85, 161, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.tePd.setFont(font)
        self.tePd.setFrameShape(QtGui.QFrame.Panel)
        self.tePd.setFrameShadow(QtGui.QFrame.Sunken)
        self.tePd.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tePd.setObjectName(_fromUtf8("tePd"))
        self.teId = QtGui.QTextEdit(self.tab_2)
        self.teId.setGeometry(QtCore.QRect(170, 131, 161, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teId.setFont(font)
        self.teId.setFrameShape(QtGui.QFrame.Panel)
        self.teId.setFrameShadow(QtGui.QFrame.Sunken)
        self.teId.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teId.setReadOnly(True)
        self.teId.setObjectName(_fromUtf8("teId"))
        self.teBdate = QtGui.QTextEdit(self.tab_2)
        self.teBdate.setGeometry(QtCore.QRect(500, 117, 211, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teBdate.setFont(font)
        self.teBdate.setFrameShape(QtGui.QFrame.Panel)
        self.teBdate.setFrameShadow(QtGui.QFrame.Sunken)
        self.teBdate.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teBdate.setObjectName(_fromUtf8("teBdate"))
        self.teTurn = QtGui.QTextEdit(self.tab_2)
        self.teTurn.setGeometry(QtCore.QRect(500, 155, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teTurn.setFont(font)
        self.teTurn.setFrameShape(QtGui.QFrame.Panel)
        self.teTurn.setFrameShadow(QtGui.QFrame.Sunken)
        self.teTurn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teTurn.setObjectName(_fromUtf8("teTurn"))
        self.teSize = QtGui.QTextEdit(self.tab_2)
        self.teSize.setGeometry(QtCore.QRect(170, 225, 161, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teSize.setFont(font)
        self.teSize.setFrameShape(QtGui.QFrame.Panel)
        self.teSize.setFrameShadow(QtGui.QFrame.Sunken)
        self.teSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teSize.setObjectName(_fromUtf8("teSize"))
        self.cbSw = QtGui.QComboBox(self.tab_2)
        self.cbSw.setGeometry(QtCore.QRect(170, 180, 161, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.cbSw.sizePolicy().hasHeightForWidth())
        self.cbSw.setSizePolicy(sizePolicy)
        self.cbSw.setMinimumSize(QtCore.QSize(0, 31))
        self.cbSw.setMaximumSize(QtCore.QSize(16777215, 31))
        self.cbSw.setSizeIncrement(QtCore.QSize(0, 11))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbSw.setFont(font)
        self.cbSw.setIconSize(QtCore.QSize(17, 17))
        self.cbSw.setObjectName(_fromUtf8("cbSw"))
        self.cbSw.addItem(_fromUtf8(""))
        self.cbSw.addItem(_fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 40, 101, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_30 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_2.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_2.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_2.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_2.addWidget(self.label_35)
        self.teBdepth = QtGui.QTextEdit(self.tab_2)
        self.teBdepth.setGeometry(QtCore.QRect(500, 80, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teBdepth.setFont(font)
        self.teBdepth.setFrameShape(QtGui.QFrame.Panel)
        self.teBdepth.setFrameShadow(QtGui.QFrame.Sunken)
        self.teBdepth.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teBdepth.setObjectName(_fromUtf8("teBdepth"))
        self.teTime = QtGui.QTextEdit(self.tab_2)
        self.teTime.setGeometry(QtCore.QRect(500, 192, 211, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teTime.setFont(font)
        self.teTime.setFrameShape(QtGui.QFrame.Panel)
        self.teTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.teTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teTime.setObjectName(_fromUtf8("teTime"))
        self.teRemark = QtGui.QTextEdit(self.tab_2)
        self.teRemark.setGeometry(QtCore.QRect(500, 230, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.teRemark.setFont(font)
        self.teRemark.setFrameShape(QtGui.QFrame.Panel)
        self.teRemark.setFrameShadow(QtGui.QFrame.Sunken)
        self.teRemark.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teRemark.setObjectName(_fromUtf8("teRemark"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 40, 101, 221))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_27 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout.addWidget(self.label_28)
        self.cbVtype = QtGui.QComboBox(self.tab_2)
        self.cbVtype.setGeometry(QtCore.QRect(330, 220, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.cbVtype.setFont(font)
        self.cbVtype.setObjectName(_fromUtf8("cbVtype"))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.cbVtype.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.ckPosmap = QtGui.QCheckBox(HydrantAttribute)
        self.ckPosmap.setGeometry(QtCore.QRect(10, 863, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.ckPosmap.setFont(font)
        self.ckPosmap.setObjectName(_fromUtf8("ckPosmap"))
        self.ckMemo = QtGui.QCheckBox(HydrantAttribute)
        self.ckMemo.setGeometry(QtCore.QRect(110, 863, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.ckMemo.setFont(font)
        self.ckMemo.setObjectName(_fromUtf8("ckMemo"))
        self.btExport = QtGui.QPushButton(HydrantAttribute)
        self.btExport.setGeometry(QtCore.QRect(210, 858, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btExport.setFont(font)
        self.btExport.setObjectName(_fromUtf8("btExport"))
        self.pushButtonCancel = QtGui.QPushButton(HydrantAttribute)
        self.pushButtonCancel.setGeometry(QtCore.QRect(650, 858, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.teVx = QtGui.QTextEdit(HydrantAttribute)
        self.teVx.setGeometry(QtCore.QRect(340, 860, 20, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teVx.setFont(font)
        self.teVx.setFrameShape(QtGui.QFrame.Panel)
        self.teVx.setFrameShadow(QtGui.QFrame.Sunken)
        self.teVx.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teVx.setObjectName(_fromUtf8("teVx"))
        self.teVy = QtGui.QTextEdit(HydrantAttribute)
        self.teVy.setGeometry(QtCore.QRect(370, 860, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teVy.setFont(font)
        self.teVy.setFrameShape(QtGui.QFrame.Panel)
        self.teVy.setFrameShadow(QtGui.QFrame.Sunken)
        self.teVy.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teVy.setObjectName(_fromUtf8("teVy"))
        self.tegid = QtGui.QTextEdit(HydrantAttribute)
        self.tegid.setGeometry(QtCore.QRect(410, 860, 20, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.tegid.setFont(font)
        self.tegid.setFrameShape(QtGui.QFrame.Panel)
        self.tegid.setFrameShadow(QtGui.QFrame.Sunken)
        self.tegid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tegid.setObjectName(_fromUtf8("tegid"))
        self.teuid = QtGui.QTextEdit(HydrantAttribute)
        self.teuid.setGeometry(QtCore.QRect(430, 860, 20, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teuid.setFont(font)
        self.teuid.setFrameShape(QtGui.QFrame.Panel)
        self.teuid.setFrameShadow(QtGui.QFrame.Sunken)
        self.teuid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teuid.setObjectName(_fromUtf8("teuid"))

        self.retranslateUi(HydrantAttribute)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HydrantAttribute)

    def retranslateUi(self, HydrantAttribute):
        HydrantAttribute.setWindowTitle(_translate("HydrantAttribute", "消防栓屬性", None))
        self.label_hydrant_turn.setText(_translate("HydrantAttribute", "消防栓轉數", None))
        self.comboBox_hydrant_status.setItemText(0, _translate("HydrantAttribute", "0 正常", None))
        self.comboBox_hydrant_status.setItemText(1, _translate("HydrantAttribute", "1 停用", None))
        self.label_bury_loc.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">埋設位置</span></p></body></html>", None))
        self.label_hydrant_status.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">消防栓狀態</span></p></body></html>", None))
        self.lineEdit_coord_67y.setInputMask(_translate("HydrantAttribute", "9999999.999; ", None))
        self.lineEdit_coord_67y.setText(_translate("HydrantAttribute", "0000000.000", None))
        self.label_coord_97y.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">位置Ｙ坐標(TWD97)</span></p></body></html>", None))
        self.label_coord_67y.setText(_translate("HydrantAttribute", "位置Ｙ坐標(TWD67)", None))
        self.comboBox_hydrant_type.setItemText(0, _translate("HydrantAttribute", "0 地上式單口式", None))
        self.comboBox_hydrant_type.setItemText(1, _translate("HydrantAttribute", "1 地上打倒安全式.單口", None))
        self.comboBox_hydrant_type.setItemText(2, _translate("HydrantAttribute", "2 地上式雙口式", None))
        self.comboBox_hydrant_type.setItemText(3, _translate("HydrantAttribute", "3 地上打倒安全式.雙口", None))
        self.comboBox_hydrant_type.setItemText(4, _translate("HydrantAttribute", "4 地下式單口式", None))
        self.comboBox_hydrant_type.setItemText(5, _translate("HydrantAttribute", "5 地下式雙口式", None))
        self.label_const_unit.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">監造單位</span></p></body></html>", None))
        self.label_hydrant_pd.setText(_translate("HydrantAttribute", "消防栓舊編號", None))
        self.lineEdit_cvalve_turn.setInputMask(_translate("HydrantAttribute", "999; ", None))
        self.lineEdit_cvalve_turn.setPlaceholderText(_translate("HydrantAttribute", "123", None))
        self.label_cpipe_size.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">連接管口徑</span></p></body></html>", None))
        self.pushButtonOK.setText(_translate("HydrantAttribute", "儲存", None))
        self.comboBox_cvalve_sw.setItemText(0, _translate("HydrantAttribute", "0 OFF", None))
        self.comboBox_cvalve_sw.setItemText(1, _translate("HydrantAttribute", "1 ON", None))
        self.lineEdit_cpipe_size.setPlaceholderText(_translate("HydrantAttribute", "1234", None))
        self.label_hydrant_mode.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">測量註記</span></p></body></html>", None))
        self.label_outlet_size.setText(_translate("HydrantAttribute", "出水口口徑", None))
        self.lineEdit_coord_97y.setInputMask(_translate("HydrantAttribute", "9999999.999; ", None))
        self.lineEdit_coord_97y.setText(_translate("HydrantAttribute", "0000000.000", None))
        self.label_hydrant_size.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">消防栓口徑</span></p></body></html>", None))
        self.label_hydrant_sw.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">消防栓轉向</span></p></body></html>", None))
        self.label_maint_date.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">養護檢查</span></p><p><span style=\" color:#aa0000;\">日期及紀錄</span></p></body></html>", None))
        self.label_remark.setText(_translate("HydrantAttribute", "註記說明", None))
        self.lineEdit_bury_date.setPlaceholderText(_translate("HydrantAttribute", "yyyymmdd", None))
        self.label_coord_97x.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">位置Ｘ坐標(TWD97)</span></p></body></html>", None))
        self.label_firebureau_id.setText(_translate("HydrantAttribute", "消防局編號", None))
        self.label_bury_depth.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">埋設深度</span></p></body></html>", None))
        self.label_admin_unit.setText(_translate("HydrantAttribute", "所有者", None))
        self.lineEdit_hydrant_turn.setInputMask(_translate("HydrantAttribute", "9999; ", None))
        self.lineEdit_hydrant_turn.setPlaceholderText(_translate("HydrantAttribute", "1234", None))
        self.label_cvalve_model.setText(_translate("HydrantAttribute", "連接管廠牌", None))
        self.label_proj_name.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">工程名稱</span></p></body></html>", None))
        self.label_coord_67x.setText(_translate("HydrantAttribute", "位置Ｘ坐標(TWD67)", None))
        self.comboBox_hydrant_sw.setItemText(0, _translate("HydrantAttribute", "0 順時針", None))
        self.comboBox_hydrant_sw.setItemText(1, _translate("HydrantAttribute", "1 逆時針", None))
        self.label_pressure.setText(_translate("HydrantAttribute", "水壓", None))
        self.label_cvalve_sw.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">連接管轉向</span></p></body></html>", None))
        self.label_coord_97z.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">地盤高程</span></p></body></html>", None))
        self.lineEdit_coord_97x.setInputMask(_translate("HydrantAttribute", "999999.999; ", None))
        self.lineEdit_coord_97x.setText(_translate("HydrantAttribute", "000000.000", None))
        self.lineEdit_hydrant_size.setPlaceholderText(_translate("HydrantAttribute", "1234", None))
        self.label_unific_id.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">識別碼</span></p></body></html>", None))
        self.comboBox_hydrant_mode.setItemText(0, _translate("HydrantAttribute", "0 非測量", None))
        self.comboBox_hydrant_mode.setItemText(1, _translate("HydrantAttribute", "1 測量", None))
        self.comboBox_hydrant_mode.setItemText(2, _translate("HydrantAttribute", "2 合理化調整", None))
        self.label_cvalve_turn.setText(_translate("HydrantAttribute", "連接管轉數", None))
        self.label_hydrant_type.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">消防栓型態</span></p></body></html>", None))
        self.label_hydrant_id.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">消防栓編號</span></p></body></html>", None))
        self.lineEdit_outlet_size.setPlaceholderText(_translate("HydrantAttribute", "1234", None))
        self.lineEdit_coord_67x.setInputMask(_translate("HydrantAttribute", "999999.999; ", None))
        self.lineEdit_coord_67x.setText(_translate("HydrantAttribute", "000000.000", None))
        self.label_bury_date.setText(_translate("HydrantAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">埋設日期</span></p></body></html>", None))
        self.label_hydrant_model.setText(_translate("HydrantAttribute", "廠牌型號", None))
        self.btUID.setText(_translate("HydrantAttribute", "填入識別碼", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("HydrantAttribute", "屬性", None))
        self.groupBox.setTitle(_translate("HydrantAttribute", "位置描述", None))
        self.lbl_pin1.setText(_translate("HydrantAttribute", "第一支點      距【】【】公尺", None))
        self.lbl_pin2.setText(_translate("HydrantAttribute", "第二支點      距【】【】公尺", None))
        self.lbl_pin3.setText(_translate("HydrantAttribute", "第三支點      距【】【】公尺", None))
        self.groupBox_2.setTitle(_translate("HydrantAttribute", "第一支點", None))
        self.label_9.setText(_translate("HydrantAttribute", "距", None))
        self.cbP1pos.setItemText(1, _translate("HydrantAttribute", "電力桿", None))
        self.cbP1pos.setItemText(2, _translate("HydrantAttribute", "電信桿", None))
        self.cbP1pos.setItemText(3, _translate("HydrantAttribute", "電力人孔", None))
        self.cbP1pos.setItemText(4, _translate("HydrantAttribute", "電信人孔", None))
        self.cbP1pos.setItemText(5, _translate("HydrantAttribute", "電信箱座", None))
        self.cbP1pos.setItemText(6, _translate("HydrantAttribute", "路燈", None))
        self.cbP1pos.setItemText(7, _translate("HydrantAttribute", "交通號誌", None))
        self.cbP1pos.setItemText(8, _translate("HydrantAttribute", "門柱", None))
        self.cbP1pos.setItemText(9, _translate("HydrantAttribute", "屋角", None))
        self.cbP1pos.setItemText(10, _translate("HydrantAttribute", "建物", None))
        self.cbP1pos.setItemText(11, _translate("HydrantAttribute", "三角點", None))
        self.cbP1pos.setItemText(12, _translate("HydrantAttribute", "水準點", None))
        self.cbP1pos.setItemText(13, _translate("HydrantAttribute", "變電箱座", None))
        self.cbP1pos.setItemText(14, _translate("HydrantAttribute", "變壓箱座", None))
        self.cbP1pos.setItemText(15, _translate("HydrantAttribute", "安全島", None))
        self.cbP1pos.setItemText(16, _translate("HydrantAttribute", "水池", None))
        self.cbP1pos.setItemText(17, _translate("HydrantAttribute", "板牆", None))
        self.cbP1pos.setItemText(18, _translate("HydrantAttribute", "圍牆", None))
        self.cbP1pos.setItemText(19, _translate("HydrantAttribute", "路邊", None))
        self.cbP1pos.setItemText(20, _translate("HydrantAttribute", "鐵絲網", None))
        self.cbP1pos.setItemText(21, _translate("HydrantAttribute", "路標", None))
        self.cbP1pos.setItemText(22, _translate("HydrantAttribute", "其他", None))
        self.label_8.setText(_translate("HydrantAttribute", "公尺", None))
        self.label_16.setText(_translate("HydrantAttribute", "X", None))
        self.label_17.setText(_translate("HydrantAttribute", "Y", None))
        self.btP1xy.setText(_translate("HydrantAttribute", "選取支點位置", None))
        self.groupBox_3.setTitle(_translate("HydrantAttribute", "第二支點", None))
        self.label_18.setText(_translate("HydrantAttribute", "距", None))
        self.cbP2pos.setItemText(1, _translate("HydrantAttribute", "電力桿", None))
        self.cbP2pos.setItemText(2, _translate("HydrantAttribute", "電信桿", None))
        self.cbP2pos.setItemText(3, _translate("HydrantAttribute", "電力人孔", None))
        self.cbP2pos.setItemText(4, _translate("HydrantAttribute", "電信人孔", None))
        self.cbP2pos.setItemText(5, _translate("HydrantAttribute", "電信箱座", None))
        self.cbP2pos.setItemText(6, _translate("HydrantAttribute", "路燈", None))
        self.cbP2pos.setItemText(7, _translate("HydrantAttribute", "交通號誌", None))
        self.cbP2pos.setItemText(8, _translate("HydrantAttribute", "門柱", None))
        self.cbP2pos.setItemText(9, _translate("HydrantAttribute", "屋角", None))
        self.cbP2pos.setItemText(10, _translate("HydrantAttribute", "建物", None))
        self.cbP2pos.setItemText(11, _translate("HydrantAttribute", "三角點", None))
        self.cbP2pos.setItemText(12, _translate("HydrantAttribute", "水準點", None))
        self.cbP2pos.setItemText(13, _translate("HydrantAttribute", "變電箱座", None))
        self.cbP2pos.setItemText(14, _translate("HydrantAttribute", "變壓箱座", None))
        self.cbP2pos.setItemText(15, _translate("HydrantAttribute", "安全島", None))
        self.cbP2pos.setItemText(16, _translate("HydrantAttribute", "水池", None))
        self.cbP2pos.setItemText(17, _translate("HydrantAttribute", "板牆", None))
        self.cbP2pos.setItemText(18, _translate("HydrantAttribute", "圍牆", None))
        self.cbP2pos.setItemText(19, _translate("HydrantAttribute", "路邊", None))
        self.cbP2pos.setItemText(20, _translate("HydrantAttribute", "鐵絲網", None))
        self.cbP2pos.setItemText(21, _translate("HydrantAttribute", "路標", None))
        self.cbP2pos.setItemText(22, _translate("HydrantAttribute", "其他", None))
        self.label_19.setText(_translate("HydrantAttribute", "公尺", None))
        self.label_20.setText(_translate("HydrantAttribute", "X", None))
        self.label_21.setText(_translate("HydrantAttribute", "Y", None))
        self.btP2xy.setText(_translate("HydrantAttribute", "選取支點位置", None))
        self.groupBox_4.setTitle(_translate("HydrantAttribute", "第三支點", None))
        self.label_22.setText(_translate("HydrantAttribute", "距", None))
        self.cbP3pos.setItemText(1, _translate("HydrantAttribute", "電力桿", None))
        self.cbP3pos.setItemText(2, _translate("HydrantAttribute", "電信桿", None))
        self.cbP3pos.setItemText(3, _translate("HydrantAttribute", "電力人孔", None))
        self.cbP3pos.setItemText(4, _translate("HydrantAttribute", "電信人孔", None))
        self.cbP3pos.setItemText(5, _translate("HydrantAttribute", "電信箱座", None))
        self.cbP3pos.setItemText(6, _translate("HydrantAttribute", "路燈", None))
        self.cbP3pos.setItemText(7, _translate("HydrantAttribute", "交通號誌", None))
        self.cbP3pos.setItemText(8, _translate("HydrantAttribute", "門柱", None))
        self.cbP3pos.setItemText(9, _translate("HydrantAttribute", "屋角", None))
        self.cbP3pos.setItemText(10, _translate("HydrantAttribute", "建物", None))
        self.cbP3pos.setItemText(11, _translate("HydrantAttribute", "三角點", None))
        self.cbP3pos.setItemText(12, _translate("HydrantAttribute", "水準點", None))
        self.cbP3pos.setItemText(13, _translate("HydrantAttribute", "變電箱座", None))
        self.cbP3pos.setItemText(14, _translate("HydrantAttribute", "變壓箱座", None))
        self.cbP3pos.setItemText(15, _translate("HydrantAttribute", "安全島", None))
        self.cbP3pos.setItemText(16, _translate("HydrantAttribute", "水池", None))
        self.cbP3pos.setItemText(17, _translate("HydrantAttribute", "板牆", None))
        self.cbP3pos.setItemText(18, _translate("HydrantAttribute", "圍牆", None))
        self.cbP3pos.setItemText(19, _translate("HydrantAttribute", "路邊", None))
        self.cbP3pos.setItemText(20, _translate("HydrantAttribute", "鐵絲網", None))
        self.cbP3pos.setItemText(21, _translate("HydrantAttribute", "路標", None))
        self.cbP3pos.setItemText(22, _translate("HydrantAttribute", "其他", None))
        self.label_23.setText(_translate("HydrantAttribute", "公尺", None))
        self.label_24.setText(_translate("HydrantAttribute", "X", None))
        self.label_25.setText(_translate("HydrantAttribute", "Y", None))
        self.btP3xy.setText(_translate("HydrantAttribute", "選取支點位置", None))
        self.pushButtonOK_pin.setText(_translate("HydrantAttribute", "儲存", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("HydrantAttribute", "三支距", None))
        self.btPrephoto.setText(_translate("HydrantAttribute", "上一張", None))
        self.btNextphoto.setText(_translate("HydrantAttribute", "下一張", None))
        self.btOpenphoto.setText(_translate("HydrantAttribute", "開啟照片", None))
        self.lbl_photoname.setText(_translate("HydrantAttribute", "檔名：", None))
        self.pushButton_open_folder.setText(_translate("HydrantAttribute", "開啟存檔資料夾", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("HydrantAttribute", "現況圖", None))
        self.groupBox_5.setTitle(_translate("HydrantAttribute", "養護及檢查紀錄", None))
        self.label_36.setText(_translate("HydrantAttribute", "工作內容", None))
        self.label_37.setText(_translate("HydrantAttribute", "工作內容", None))
        self.label_38.setText(_translate("HydrantAttribute", "工作內容", None))
        self.label_39.setText(_translate("HydrantAttribute", "工作內容", None))
        self.label_40.setText(_translate("HydrantAttribute", "工作內容", None))
        self.label_41.setText(_translate("HydrantAttribute", "工作內容", None))
        self.label_26.setText(_translate("HydrantAttribute", "第一次日期", None))
        self.label_42.setText(_translate("HydrantAttribute", "第二次日期", None))
        self.label_43.setText(_translate("HydrantAttribute", "第三次日期", None))
        self.label_44.setText(_translate("HydrantAttribute", "第四次日期", None))
        self.label_45.setText(_translate("HydrantAttribute", "第五次日期", None))
        self.label_46.setText(_translate("HydrantAttribute", "第六次日期", None))
        self.cbSw.setItemText(0, _translate("HydrantAttribute", "順時針", None))
        self.cbSw.setItemText(1, _translate("HydrantAttribute", "逆時針", None))
        self.label_30.setText(_translate("HydrantAttribute", "埋設位置", None))
        self.label_31.setText(_translate("HydrantAttribute", "埋設深度", None))
        self.label_32.setText(_translate("HydrantAttribute", "埋設日期", None))
        self.label_33.setText(_translate("HydrantAttribute", "轉數", None))
        self.label_34.setText(_translate("HydrantAttribute", "開關時間", None))
        self.label_35.setText(_translate("HydrantAttribute", "註記說明", None))
        self.label_10.setText(_translate("HydrantAttribute", "廠牌型號", None))
        self.label_11.setText(_translate("HydrantAttribute", "舊編號", None))
        self.label_12.setText(_translate("HydrantAttribute", "閥類編號", None))
        self.label_27.setText(_translate("HydrantAttribute", "開關轉向", None))
        self.label_28.setText(_translate("HydrantAttribute", "轉向口徑", None))
        self.cbVtype.setItemText(0, _translate("HydrantAttribute", "水力自動閥", None))
        self.cbVtype.setItemText(1, _translate("HydrantAttribute", "制水閥", None))
        self.cbVtype.setItemText(2, _translate("HydrantAttribute", "制水閥(附手輪)", None))
        self.cbVtype.setItemText(3, _translate("HydrantAttribute", "底閥", None))
        self.cbVtype.setItemText(4, _translate("HydrantAttribute", "洩壓閥", None))
        self.cbVtype.setItemText(5, _translate("HydrantAttribute", "氣動閥", None))
        self.cbVtype.setItemText(6, _translate("HydrantAttribute", "浮球閥", None))
        self.cbVtype.setItemText(7, _translate("HydrantAttribute", "逆止閥", None))
        self.cbVtype.setItemText(8, _translate("HydrantAttribute", "排氣閥", None))
        self.cbVtype.setItemText(9, _translate("HydrantAttribute", "減壓、持壓閥", None))
        self.cbVtype.setItemText(10, _translate("HydrantAttribute", "電動閥", None))
        self.cbVtype.setItemText(11, _translate("HydrantAttribute", "彈性坐封閘閥", None))
        self.cbVtype.setItemText(12, _translate("HydrantAttribute", "彈性坐封閘閥(附手輪)", None))
        self.cbVtype.setItemText(13, _translate("HydrantAttribute", "蝶閥(豎式)", None))
        self.cbVtype.setItemText(14, _translate("HydrantAttribute", "蝶閥(橫軸式)", None))
        self.ckPosmap.setText(_translate("HydrantAttribute", "位置圖", None))
        self.ckMemo.setText(_translate("HydrantAttribute", "記錄卡", None))
        self.btExport.setText(_translate("HydrantAttribute", "轉出圖卡", None))
        self.pushButtonCancel.setText(_translate("HydrantAttribute", "取消", None))

