# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_valve_attribute.ui'
#
# Created: Wed Nov 21 14:53:53 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ValveAttribute(object):
    def setupUi(self, ValveAttribute):
        ValveAttribute.setObjectName(_fromUtf8("ValveAttribute"))
        ValveAttribute.setWindowModality(QtCore.Qt.NonModal)
        ValveAttribute.resize(801, 833)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("AcadEref"))
        font.setPointSize(12)
        ValveAttribute.setFont(font)
        ValveAttribute.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        ValveAttribute.setToolTip(_fromUtf8(""))
        ValveAttribute.setModal(False)
        self.tabWidget = QtGui.QTabWidget(ValveAttribute)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 781, 771))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_valve_status = QtGui.QLabel(self.tab_4)
        self.label_valve_status.setGeometry(QtCore.QRect(268, 68, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_status.setFont(font)
        self.label_valve_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_status.setObjectName(_fromUtf8("label_valve_status"))
        self.comboBox_valve_sw = QtGui.QComboBox(self.tab_4)
        self.comboBox_valve_sw.setGeometry(QtCore.QRect(620, 68, 136, 32))
        self.comboBox_valve_sw.setObjectName(_fromUtf8("comboBox_valve_sw"))
        self.comboBox_valve_sw.addItem(_fromUtf8(""))
        self.comboBox_valve_sw.addItem(_fromUtf8(""))
        self.label_monit_name = QtGui.QLabel(self.tab_4)
        self.label_monit_name.setGeometry(QtCore.QRect(516, 308, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_monit_name.setFont(font)
        self.label_monit_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_monit_name.setObjectName(_fromUtf8("label_monit_name"))
        self.lineEdit_bury_date = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_bury_date.setGeometry(QtCore.QRect(620, 188, 136, 32))
        self.lineEdit_bury_date.setMaxLength(8)
        self.lineEdit_bury_date.setObjectName(_fromUtf8("lineEdit_bury_date"))
        self.comboBox_valve_mode = QtGui.QComboBox(self.tab_4)
        self.comboBox_valve_mode.setGeometry(QtCore.QRect(284, 564, 136, 32))
        self.comboBox_valve_mode.setObjectName(_fromUtf8("comboBox_valve_mode"))
        self.comboBox_valve_mode.addItem(_fromUtf8(""))
        self.comboBox_valve_mode.addItem(_fromUtf8(""))
        self.comboBox_valve_mode.addItem(_fromUtf8(""))
        self.label_valve_type = QtGui.QLabel(self.tab_4)
        self.label_valve_type.setGeometry(QtCore.QRect(388, 28, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_type.setFont(font)
        self.label_valve_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_type.setObjectName(_fromUtf8("label_valve_type"))
        self.lineEdit_valve_id = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_valve_id.setGeometry(QtCore.QRect(124, 68, 136, 32))
        self.lineEdit_valve_id.setMaxLength(15)
        self.lineEdit_valve_id.setObjectName(_fromUtf8("lineEdit_valve_id"))
        self.lineEdit_coord_97x = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_97x.setGeometry(QtCore.QRect(284, 644, 136, 32))
        self.lineEdit_coord_97x.setObjectName(_fromUtf8("lineEdit_coord_97x"))
        self.label_valve_pd = QtGui.QLabel(self.tab_4)
        self.label_valve_pd.setGeometry(QtCore.QRect(380, 110, 61, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_pd.setFont(font)
        self.label_valve_pd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_pd.setObjectName(_fromUtf8("label_valve_pd"))
        self.lineEdit_coord_97y = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_97y.setGeometry(QtCore.QRect(620, 644, 136, 32))
        self.lineEdit_coord_97y.setObjectName(_fromUtf8("lineEdit_coord_97y"))
        self.label_coord_97x = QtGui.QLabel(self.tab_4)
        self.label_coord_97x.setGeometry(QtCore.QRect(105, 644, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_97x.setFont(font)
        self.label_coord_97x.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_97x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_97x.setObjectName(_fromUtf8("label_coord_97x"))
        self.comboBox_valve_status = QtGui.QComboBox(self.tab_4)
        self.comboBox_valve_status.setGeometry(QtCore.QRect(372, 68, 136, 32))
        self.comboBox_valve_status.setObjectName(_fromUtf8("comboBox_valve_status"))
        self.comboBox_valve_status.addItem(_fromUtf8(""))
        self.comboBox_valve_status.addItem(_fromUtf8(""))
        self.comboBox_valve_status.addItem(_fromUtf8(""))
        self.comboBox_valve_status.addItem(_fromUtf8(""))
        self.lineEdit_valve_turn = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_valve_turn.setGeometry(QtCore.QRect(620, 148, 136, 32))
        self.lineEdit_valve_turn.setObjectName(_fromUtf8("lineEdit_valve_turn"))
        self.lineEdit_valve_pd = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_valve_pd.setGeometry(QtCore.QRect(445, 108, 311, 32))
        self.lineEdit_valve_pd.setText(_fromUtf8(""))
        self.lineEdit_valve_pd.setMaxLength(20)
        self.lineEdit_valve_pd.setObjectName(_fromUtf8("lineEdit_valve_pd"))
        self.label_coord_67y = QtGui.QLabel(self.tab_4)
        self.label_coord_67y.setGeometry(QtCore.QRect(441, 604, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_67y.setFont(font)
        self.label_coord_67y.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_67y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_67y.setObjectName(_fromUtf8("label_coord_67y"))
        self.comboBox_unific_id = QtGui.QComboBox(self.tab_4)
        self.comboBox_unific_id.setGeometry(QtCore.QRect(370, 28, 21, 32))
        self.comboBox_unific_id.setObjectName(_fromUtf8("comboBox_unific_id"))
        self.plainTextEdit_maint_rec = QtGui.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_maint_rec.setGeometry(QtCore.QRect(40, 570, 31, 31))
        self.plainTextEdit_maint_rec.setObjectName(_fromUtf8("plainTextEdit_maint_rec"))
        self.label_valve_model = QtGui.QLabel(self.tab_4)
        self.label_valve_model.setGeometry(QtCore.QRect(20, 108, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_model.setFont(font)
        self.label_valve_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_model.setObjectName(_fromUtf8("label_valve_model"))
        self.label_valve_id = QtGui.QLabel(self.tab_4)
        self.label_valve_id.setGeometry(QtCore.QRect(20, 68, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_id.setFont(font)
        self.label_valve_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_id.setObjectName(_fromUtf8("label_valve_id"))
        self.lineEdit_coord_67y = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_67y.setGeometry(QtCore.QRect(620, 604, 136, 32))
        self.lineEdit_coord_67y.setObjectName(_fromUtf8("lineEdit_coord_67y"))
        self.label_proj_name = QtGui.QLabel(self.tab_4)
        self.label_proj_name.setGeometry(QtCore.QRect(20, 268, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_proj_name.setFont(font)
        self.label_proj_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_proj_name.setObjectName(_fromUtf8("label_proj_name"))
        self.lineEdit_coord_67x = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_67x.setGeometry(QtCore.QRect(284, 604, 136, 32))
        self.lineEdit_coord_67x.setObjectName(_fromUtf8("lineEdit_coord_67x"))
        self.label_valve_time = QtGui.QLabel(self.tab_4)
        self.label_valve_time.setGeometry(QtCore.QRect(20, 188, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_time.setFont(font)
        self.label_valve_time.setFrameShape(QtGui.QFrame.Box)
        self.label_valve_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_time.setObjectName(_fromUtf8("label_valve_time"))
        self.lineEdit_valve_time = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_valve_time.setGeometry(QtCore.QRect(124, 188, 136, 32))
        self.lineEdit_valve_time.setObjectName(_fromUtf8("lineEdit_valve_time"))
        self.lineEdit_bury_depth = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_bury_depth.setGeometry(QtCore.QRect(372, 188, 136, 32))
        self.lineEdit_bury_depth.setInputMask(_fromUtf8(""))
        self.lineEdit_bury_depth.setText(_fromUtf8(""))
        self.lineEdit_bury_depth.setObjectName(_fromUtf8("lineEdit_bury_depth"))
        self.label_valve_turn = QtGui.QLabel(self.tab_4)
        self.label_valve_turn.setGeometry(QtCore.QRect(516, 148, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_turn.setFont(font)
        self.label_valve_turn.setFrameShape(QtGui.QFrame.Box)
        self.label_valve_turn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_turn.setObjectName(_fromUtf8("label_valve_turn"))
        self.lineEdit_monit_name = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_monit_name.setGeometry(QtCore.QRect(620, 308, 136, 32))
        self.lineEdit_monit_name.setMaxLength(10)
        self.lineEdit_monit_name.setObjectName(_fromUtf8("lineEdit_monit_name"))
        self.lineEdit_valve_model = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_valve_model.setGeometry(QtCore.QRect(124, 108, 231, 32))
        self.lineEdit_valve_model.setMaxLength(20)
        self.lineEdit_valve_model.setObjectName(_fromUtf8("lineEdit_valve_model"))
        self.comboBox_valve_type = QtGui.QComboBox(self.tab_4)
        self.comboBox_valve_type.setGeometry(QtCore.QRect(492, 28, 264, 32))
        self.comboBox_valve_type.setObjectName(_fromUtf8("comboBox_valve_type"))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.comboBox_valve_type.addItem(_fromUtf8(""))
        self.label_bury_loc = QtGui.QLabel(self.tab_4)
        self.label_bury_loc.setGeometry(QtCore.QRect(20, 228, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bury_loc.setFont(font)
        self.label_bury_loc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bury_loc.setObjectName(_fromUtf8("label_bury_loc"))
        self.label_valve_size = QtGui.QLabel(self.tab_4)
        self.label_valve_size.setGeometry(QtCore.QRect(268, 148, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_size.setFont(font)
        self.label_valve_size.setFrameShape(QtGui.QFrame.Box)
        self.label_valve_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_size.setObjectName(_fromUtf8("label_valve_size"))
        self.lineEdit_coord_97z = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_coord_97z.setGeometry(QtCore.QRect(620, 564, 136, 32))
        self.lineEdit_coord_97z.setInputMask(_fromUtf8(""))
        self.lineEdit_coord_97z.setText(_fromUtf8(""))
        self.lineEdit_coord_97z.setObjectName(_fromUtf8("lineEdit_coord_97z"))
        self.label_bury_depth = QtGui.QLabel(self.tab_4)
        self.label_bury_depth.setGeometry(QtCore.QRect(268, 188, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bury_depth.setFont(font)
        self.label_bury_depth.setFrameShape(QtGui.QFrame.Box)
        self.label_bury_depth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bury_depth.setObjectName(_fromUtf8("label_bury_depth"))
        self.label_angle = QtGui.QLabel(self.tab_4)
        self.label_angle.setGeometry(QtCore.QRect(20, 148, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_angle.setFont(font)
        self.label_angle.setFrameShape(QtGui.QFrame.Box)
        self.label_angle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_angle.setObjectName(_fromUtf8("label_angle"))
        self.label_const_unit = QtGui.QLabel(self.tab_4)
        self.label_const_unit.setGeometry(QtCore.QRect(20, 308, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_const_unit.setFont(font)
        self.label_const_unit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_const_unit.setObjectName(_fromUtf8("label_const_unit"))
        self.label_remark = QtGui.QLabel(self.tab_4)
        self.label_remark.setGeometry(QtCore.QRect(20, 524, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_remark.setFont(font)
        self.label_remark.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_remark.setObjectName(_fromUtf8("label_remark"))
        self.label_valve_mode = QtGui.QLabel(self.tab_4)
        self.label_valve_mode.setGeometry(QtCore.QRect(124, 564, 152, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_mode.setFont(font)
        self.label_valve_mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_mode.setObjectName(_fromUtf8("label_valve_mode"))
        self.label_bury_date = QtGui.QLabel(self.tab_4)
        self.label_bury_date.setGeometry(QtCore.QRect(516, 188, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_bury_date.setFont(font)
        self.label_bury_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bury_date.setObjectName(_fromUtf8("label_bury_date"))
        self.label_unific_id = QtGui.QLabel(self.tab_4)
        self.label_unific_id.setGeometry(QtCore.QRect(20, 28, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_unific_id.setFont(font)
        self.label_unific_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_unific_id.setObjectName(_fromUtf8("label_unific_id"))
        self.pushButtonOK = QtGui.QPushButton(self.tab_4)
        self.pushButtonOK.setGeometry(QtCore.QRect(630, 690, 136, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.label_coord_97z = QtGui.QLabel(self.tab_4)
        self.label_coord_97z.setGeometry(QtCore.QRect(441, 564, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_97z.setFont(font)
        self.label_coord_97z.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_97z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_97z.setObjectName(_fromUtf8("label_coord_97z"))
        self.label_coord_97y = QtGui.QLabel(self.tab_4)
        self.label_coord_97y.setGeometry(QtCore.QRect(441, 644, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_97y.setFont(font)
        self.label_coord_97y.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_97y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_97y.setObjectName(_fromUtf8("label_coord_97y"))
        self.label_coord_67x = QtGui.QLabel(self.tab_4)
        self.label_coord_67x.setGeometry(QtCore.QRect(105, 604, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_coord_67x.setFont(font)
        self.label_coord_67x.setFrameShape(QtGui.QFrame.Box)
        self.label_coord_67x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_coord_67x.setObjectName(_fromUtf8("label_coord_67x"))
        self.lineEdit_angle = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_angle.setGeometry(QtCore.QRect(124, 148, 136, 32))
        self.lineEdit_angle.setInputMask(_fromUtf8(""))
        self.lineEdit_angle.setText(_fromUtf8(""))
        self.lineEdit_angle.setObjectName(_fromUtf8("lineEdit_angle"))
        self.label_valve_sw = QtGui.QLabel(self.tab_4)
        self.label_valve_sw.setGeometry(QtCore.QRect(516, 68, 96, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_valve_sw.setFont(font)
        self.label_valve_sw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_valve_sw.setObjectName(_fromUtf8("label_valve_sw"))
        self.label_maint_date = QtGui.QLabel(self.tab_4)
        self.label_maint_date.setGeometry(QtCore.QRect(20, 380, 96, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_maint_date.setFont(font)
        self.label_maint_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_maint_date.setObjectName(_fromUtf8("label_maint_date"))
        self.lineEdit_valve_size = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_valve_size.setGeometry(QtCore.QRect(372, 148, 136, 32))
        self.lineEdit_valve_size.setInputMask(_fromUtf8(""))
        self.lineEdit_valve_size.setMaxLength(4)
        self.lineEdit_valve_size.setObjectName(_fromUtf8("lineEdit_valve_size"))
        self.lineEdit_bury_loc = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_bury_loc.setGeometry(QtCore.QRect(124, 228, 632, 32))
        self.lineEdit_bury_loc.setMaxLength(50)
        self.lineEdit_bury_loc.setObjectName(_fromUtf8("lineEdit_bury_loc"))
        self.lineEdit_proj_name = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_proj_name.setGeometry(QtCore.QRect(124, 268, 632, 32))
        self.lineEdit_proj_name.setMaxLength(50)
        self.lineEdit_proj_name.setObjectName(_fromUtf8("lineEdit_proj_name"))
        self.plainTextEdit_maint_date = QtGui.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_maint_date.setGeometry(QtCore.QRect(40, 610, 31, 31))
        self.plainTextEdit_maint_date.setObjectName(_fromUtf8("plainTextEdit_maint_date"))
        self.lineEdit_remark = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_remark.setGeometry(QtCore.QRect(124, 524, 632, 32))
        self.lineEdit_remark.setMaxLength(50)
        self.lineEdit_remark.setObjectName(_fromUtf8("lineEdit_remark"))
        self.lineEdit_const_unit = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_const_unit.setGeometry(QtCore.QRect(124, 308, 384, 32))
        self.lineEdit_const_unit.setMaxLength(30)
        self.lineEdit_const_unit.setObjectName(_fromUtf8("lineEdit_const_unit"))
        self.lineEdit_unific_id = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_unific_id.setGeometry(QtCore.QRect(120, 28, 251, 32))
        self.lineEdit_unific_id.setMaxLength(22)
        self.lineEdit_unific_id.setObjectName(_fromUtf8("lineEdit_unific_id"))
        self.listWidget_maint_date = QtGui.QListWidget(self.tab_4)
        self.listWidget_maint_date.setGeometry(QtCore.QRect(124, 350, 631, 161))
        self.listWidget_maint_date.setObjectName(_fromUtf8("listWidget_maint_date"))
        self.btUID = QtGui.QPushButton(self.tab_4)
        self.btUID.setGeometry(QtCore.QRect(500, 690, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btUID.setFont(font)
        self.btUID.setObjectName(_fromUtf8("btUID"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(80, 40, 621, 131))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lbl_pin1 = QtGui.QLabel(self.groupBox)
        self.lbl_pin1.setGeometry(QtCore.QRect(20, 30, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_pin1.setFont(font)
        self.lbl_pin1.setObjectName(_fromUtf8("lbl_pin1"))
        self.lbl_pin2 = QtGui.QLabel(self.groupBox)
        self.lbl_pin2.setGeometry(QtCore.QRect(20, 60, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_pin2.setFont(font)
        self.lbl_pin2.setObjectName(_fromUtf8("lbl_pin2"))
        self.lbl_pin3 = QtGui.QLabel(self.groupBox)
        self.lbl_pin3.setGeometry(QtCore.QRect(20, 90, 581, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_pin3.setFont(font)
        self.lbl_pin3.setObjectName(_fromUtf8("lbl_pin3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 180, 621, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.teP1disc = QtGui.QTextEdit(self.groupBox_2)
        self.teP1disc.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.teP1disc.setFont(font)
        self.teP1disc.setFrameShape(QtGui.QFrame.Panel)
        self.teP1disc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1disc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1disc.setObjectName(_fromUtf8("teP1disc"))
        self.cbP1pos = QtGui.QComboBox(self.groupBox_2)
        self.cbP1pos.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbP1pos.setFont(font)
        self.cbP1pos.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cbP1pos.setObjectName(_fromUtf8("cbP1pos"))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.setItemText(0, _fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.cbP1pos.addItem(_fromUtf8(""))
        self.teP1dis = QtGui.QTextEdit(self.groupBox_2)
        self.teP1dis.setGeometry(QtCore.QRect(470, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP1dis.setFont(font)
        self.teP1dis.setFrameShape(QtGui.QFrame.Panel)
        self.teP1dis.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1dis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1dis.setObjectName(_fromUtf8("teP1dis"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(560, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.teP1x = QtGui.QTextEdit(self.groupBox_2)
        self.teP1x.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP1x.setFont(font)
        self.teP1x.setFrameShape(QtGui.QFrame.Panel)
        self.teP1x.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1x.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1x.setObjectName(_fromUtf8("teP1x"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(250, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.teP1y = QtGui.QTextEdit(self.groupBox_2)
        self.teP1y.setGeometry(QtCore.QRect(270, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP1y.setFont(font)
        self.teP1y.setFrameShape(QtGui.QFrame.Panel)
        self.teP1y.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP1y.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP1y.setObjectName(_fromUtf8("teP1y"))
        self.btP1xy = QtGui.QPushButton(self.groupBox_2)
        self.btP1xy.setGeometry(QtCore.QRect(470, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.btP1xy.setFont(font)
        self.btP1xy.setObjectName(_fromUtf8("btP1xy"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(80, 300, 621, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.teP2disc = QtGui.QTextEdit(self.groupBox_3)
        self.teP2disc.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2disc.setFont(font)
        self.teP2disc.setFrameShape(QtGui.QFrame.Panel)
        self.teP2disc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2disc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2disc.setObjectName(_fromUtf8("teP2disc"))
        self.cbP2pos = QtGui.QComboBox(self.groupBox_3)
        self.cbP2pos.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbP2pos.setFont(font)
        self.cbP2pos.setObjectName(_fromUtf8("cbP2pos"))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.setItemText(0, _fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.cbP2pos.addItem(_fromUtf8(""))
        self.teP2dis = QtGui.QTextEdit(self.groupBox_3)
        self.teP2dis.setGeometry(QtCore.QRect(470, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2dis.setFont(font)
        self.teP2dis.setFrameShape(QtGui.QFrame.Panel)
        self.teP2dis.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2dis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2dis.setObjectName(_fromUtf8("teP2dis"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(560, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.teP2x = QtGui.QTextEdit(self.groupBox_3)
        self.teP2x.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2x.setFont(font)
        self.teP2x.setFrameShape(QtGui.QFrame.Panel)
        self.teP2x.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2x.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2x.setObjectName(_fromUtf8("teP2x"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(250, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.teP2y = QtGui.QTextEdit(self.groupBox_3)
        self.teP2y.setGeometry(QtCore.QRect(270, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP2y.setFont(font)
        self.teP2y.setFrameShape(QtGui.QFrame.Panel)
        self.teP2y.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP2y.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP2y.setObjectName(_fromUtf8("teP2y"))
        self.btP2xy = QtGui.QPushButton(self.groupBox_3)
        self.btP2xy.setGeometry(QtCore.QRect(470, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.btP2xy.setFont(font)
        self.btP2xy.setObjectName(_fromUtf8("btP2xy"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(80, 420, 621, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.teP3disc = QtGui.QTextEdit(self.groupBox_4)
        self.teP3disc.setGeometry(QtCore.QRect(40, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.teP3disc.setFont(font)
        self.teP3disc.setFrameShape(QtGui.QFrame.Panel)
        self.teP3disc.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3disc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3disc.setObjectName(_fromUtf8("teP3disc"))
        self.cbP3pos = QtGui.QComboBox(self.groupBox_4)
        self.cbP3pos.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.cbP3pos.setFont(font)
        self.cbP3pos.setObjectName(_fromUtf8("cbP3pos"))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.setItemText(0, _fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.cbP3pos.addItem(_fromUtf8(""))
        self.teP3dis = QtGui.QTextEdit(self.groupBox_4)
        self.teP3dis.setGeometry(QtCore.QRect(470, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP3dis.setFont(font)
        self.teP3dis.setFrameShape(QtGui.QFrame.Panel)
        self.teP3dis.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3dis.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3dis.setObjectName(_fromUtf8("teP3dis"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(560, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.teP3x = QtGui.QTextEdit(self.groupBox_4)
        self.teP3x.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP3x.setFont(font)
        self.teP3x.setFrameShape(QtGui.QFrame.Panel)
        self.teP3x.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3x.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3x.setObjectName(_fromUtf8("teP3x"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(250, 70, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.teP3y = QtGui.QTextEdit(self.groupBox_4)
        self.teP3y.setGeometry(QtCore.QRect(270, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teP3y.setFont(font)
        self.teP3y.setFrameShape(QtGui.QFrame.Panel)
        self.teP3y.setFrameShadow(QtGui.QFrame.Sunken)
        self.teP3y.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teP3y.setObjectName(_fromUtf8("teP3y"))
        self.btP3xy = QtGui.QPushButton(self.groupBox_4)
        self.btP3xy.setGeometry(QtCore.QRect(470, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.btP3xy.setFont(font)
        self.btP3xy.setObjectName(_fromUtf8("btP3xy"))
        self.pushButtonOK_valve_pin = QtGui.QPushButton(self.tab)
        self.pushButtonOK_valve_pin.setGeometry(QtCore.QRect(310, 560, 136, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOK_valve_pin.setFont(font)
        self.pushButtonOK_valve_pin.setObjectName(_fromUtf8("pushButtonOK_valve_pin"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gvPhoto = QtGui.QGraphicsView(self.tab_3)
        self.gvPhoto.setGeometry(QtCore.QRect(10, 10, 751, 661))
        self.gvPhoto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvPhoto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gvPhoto.setInteractive(False)
        self.gvPhoto.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.gvPhoto.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.gvPhoto.setObjectName(_fromUtf8("gvPhoto"))
        self.btPrephoto = QtGui.QPushButton(self.tab_3)
        self.btPrephoto.setGeometry(QtCore.QRect(490, 690, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btPrephoto.setFont(font)
        self.btPrephoto.setObjectName(_fromUtf8("btPrephoto"))
        self.btNextphoto = QtGui.QPushButton(self.tab_3)
        self.btNextphoto.setGeometry(QtCore.QRect(570, 690, 71, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btNextphoto.setFont(font)
        self.btNextphoto.setObjectName(_fromUtf8("btNextphoto"))
        self.btOpenphoto = QtGui.QPushButton(self.tab_3)
        self.btOpenphoto.setGeometry(QtCore.QRect(650, 690, 91, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btOpenphoto.setFont(font)
        self.btOpenphoto.setObjectName(_fromUtf8("btOpenphoto"))
        self.lbl_photoname = QtGui.QLabel(self.tab_3)
        self.lbl_photoname.setGeometry(QtCore.QRect(10, 670, 361, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.lbl_photoname.setFont(font)
        self.lbl_photoname.setObjectName(_fromUtf8("lbl_photoname"))
        self.pushButton_open_folder = QtGui.QPushButton(self.tab_3)
        self.pushButton_open_folder.setGeometry(QtCore.QRect(10, 700, 221, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_open_folder.setFont(font)
        self.pushButton_open_folder.setObjectName(_fromUtf8("pushButton_open_folder"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_current_path = QtGui.QLabel(self.tab_2)
        self.label_current_path.setGeometry(QtCore.QRect(10, 10, 531, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_current_path.setFont(font)
        self.label_current_path.setFrameShape(QtGui.QFrame.Box)
        self.label_current_path.setText(_fromUtf8(""))
        self.label_current_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_current_path.setObjectName(_fromUtf8("label_current_path"))
        self.pushButton_select_folder = QtGui.QPushButton(self.tab_2)
        self.pushButton_select_folder.setGeometry(QtCore.QRect(550, 10, 221, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_folder.setFont(font)
        self.pushButton_select_folder.setObjectName(_fromUtf8("pushButton_select_folder"))
        self.listWidget_folder = QtGui.QListWidget(self.tab_2)
        self.listWidget_folder.setGeometry(QtCore.QRect(10, 50, 311, 681))
        self.listWidget_folder.setObjectName(_fromUtf8("listWidget_folder"))
        self.pushButton_save = QtGui.QPushButton(self.tab_2)
        self.pushButton_save.setGeometry(QtCore.QRect(550, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.label_img_preview = QtGui.QLabel(self.tab_2)
        self.label_img_preview.setGeometry(QtCore.QRect(329, 279, 441, 451))
        self.label_img_preview.setFrameShape(QtGui.QFrame.Box)
        self.label_img_preview.setFrameShadow(QtGui.QFrame.Raised)
        self.label_img_preview.setText(_fromUtf8(""))
        self.label_img_preview.setObjectName(_fromUtf8("label_img_preview"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.ckPosmap = QtGui.QCheckBox(ValveAttribute)
        self.ckPosmap.setGeometry(QtCore.QRect(10, 795, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.ckPosmap.setFont(font)
        self.ckPosmap.setChecked(False)
        self.ckPosmap.setObjectName(_fromUtf8("ckPosmap"))
        self.ckMemo = QtGui.QCheckBox(ValveAttribute)
        self.ckMemo.setGeometry(QtCore.QRect(100, 795, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        self.ckMemo.setFont(font)
        self.ckMemo.setChecked(False)
        self.ckMemo.setObjectName(_fromUtf8("ckMemo"))
        self.btExport = QtGui.QPushButton(ValveAttribute)
        self.btExport.setGeometry(QtCore.QRect(190, 790, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.btExport.setFont(font)
        self.btExport.setObjectName(_fromUtf8("btExport"))
        self.teVy = QtGui.QTextEdit(ValveAttribute)
        self.teVy.setGeometry(QtCore.QRect(370, 790, 21, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teVy.setFont(font)
        self.teVy.setFrameShape(QtGui.QFrame.Panel)
        self.teVy.setFrameShadow(QtGui.QFrame.Sunken)
        self.teVy.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teVy.setObjectName(_fromUtf8("teVy"))
        self.teVx = QtGui.QTextEdit(ValveAttribute)
        self.teVx.setGeometry(QtCore.QRect(340, 790, 20, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teVx.setFont(font)
        self.teVx.setFrameShape(QtGui.QFrame.Panel)
        self.teVx.setFrameShadow(QtGui.QFrame.Sunken)
        self.teVx.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teVx.setObjectName(_fromUtf8("teVx"))
        self.teuid = QtGui.QTextEdit(ValveAttribute)
        self.teuid.setGeometry(QtCore.QRect(430, 790, 20, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.teuid.setFont(font)
        self.teuid.setFrameShape(QtGui.QFrame.Panel)
        self.teuid.setFrameShadow(QtGui.QFrame.Sunken)
        self.teuid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.teuid.setObjectName(_fromUtf8("teuid"))
        self.tegid = QtGui.QTextEdit(ValveAttribute)
        self.tegid.setGeometry(QtCore.QRect(410, 790, 20, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(12)
        self.tegid.setFont(font)
        self.tegid.setFrameShape(QtGui.QFrame.Panel)
        self.tegid.setFrameShadow(QtGui.QFrame.Sunken)
        self.tegid.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tegid.setObjectName(_fromUtf8("tegid"))
        self.pushButtonCancel = QtGui.QPushButton(ValveAttribute)
        self.pushButtonCancel.setGeometry(QtCore.QRect(650, 790, 136, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))

        self.retranslateUi(ValveAttribute)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ValveAttribute)

    def retranslateUi(self, ValveAttribute):
        ValveAttribute.setWindowTitle(_translate("ValveAttribute", "閥屬性", None))
        self.label_valve_status.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">閥類狀態</span></p></body></html>", None))
        self.comboBox_valve_sw.setItemText(0, _translate("ValveAttribute", "0 順時針", None))
        self.comboBox_valve_sw.setItemText(1, _translate("ValveAttribute", "1 逆時針", None))
        self.label_monit_name.setText(_translate("ValveAttribute", "監工員", None))
        self.comboBox_valve_mode.setItemText(0, _translate("ValveAttribute", "0 非測量", None))
        self.comboBox_valve_mode.setItemText(1, _translate("ValveAttribute", "1 測量", None))
        self.comboBox_valve_mode.setItemText(2, _translate("ValveAttribute", "2 合理化調整", None))
        self.label_valve_type.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">閥類型態</span></p></body></html>", None))
        self.lineEdit_coord_97x.setInputMask(_translate("ValveAttribute", "999999.999; ", None))
        self.lineEdit_coord_97x.setText(_translate("ValveAttribute", "000000.000", None))
        self.label_valve_pd.setText(_translate("ValveAttribute", "舊編號", None))
        self.lineEdit_coord_97y.setInputMask(_translate("ValveAttribute", "9999999.999; ", None))
        self.lineEdit_coord_97y.setText(_translate("ValveAttribute", "0000000.000", None))
        self.label_coord_97x.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">位置Ｘ坐標(TWD97)</span></p></body></html>", None))
        self.comboBox_valve_status.setItemText(0, _translate("ValveAttribute", "0 正常", None))
        self.comboBox_valve_status.setItemText(1, _translate("ValveAttribute", "1 停用", None))
        self.comboBox_valve_status.setItemText(2, _translate("ValveAttribute", "2 A", None))
        self.comboBox_valve_status.setItemText(3, _translate("ValveAttribute", "3 M", None))
        self.lineEdit_valve_turn.setInputMask(_translate("ValveAttribute", "9999; ", None))
        self.label_coord_67y.setText(_translate("ValveAttribute", "位置Ｙ坐標(TWD67)", None))
        self.label_valve_model.setText(_translate("ValveAttribute", "廠牌型號", None))
        self.label_valve_id.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">閥類編號</span></p></body></html>", None))
        self.lineEdit_coord_67y.setInputMask(_translate("ValveAttribute", "9999999.999; ", None))
        self.lineEdit_coord_67y.setText(_translate("ValveAttribute", "0000000.000", None))
        self.label_proj_name.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">工程名稱</span></p></body></html>", None))
        self.lineEdit_coord_67x.setInputMask(_translate("ValveAttribute", "999999.999; ", None))
        self.lineEdit_coord_67x.setText(_translate("ValveAttribute", "000000.000", None))
        self.label_valve_time.setText(_translate("ValveAttribute", "開關時間", None))
        self.lineEdit_valve_time.setInputMask(_translate("ValveAttribute", "9999; ", None))
        self.label_valve_turn.setText(_translate("ValveAttribute", "轉數", None))
        self.comboBox_valve_type.setItemText(0, _translate("ValveAttribute", "0 制水閥", None))
        self.comboBox_valve_type.setItemText(1, _translate("ValveAttribute", "1 制水閥(附手輪)", None))
        self.comboBox_valve_type.setItemText(2, _translate("ValveAttribute", "2 彈性坐封閘閥", None))
        self.comboBox_valve_type.setItemText(3, _translate("ValveAttribute", "3 彈性坐封閘閥(附手輪)", None))
        self.comboBox_valve_type.setItemText(4, _translate("ValveAttribute", "4 蝶閥(豎式)", None))
        self.comboBox_valve_type.setItemText(5, _translate("ValveAttribute", "5 蝶閥(橫軸式)", None))
        self.comboBox_valve_type.setItemText(6, _translate("ValveAttribute", "6 電動閥", None))
        self.comboBox_valve_type.setItemText(7, _translate("ValveAttribute", "7 浮球閥", None))
        self.comboBox_valve_type.setItemText(8, _translate("ValveAttribute", "8 底閥", None))
        self.comboBox_valve_type.setItemText(9, _translate("ValveAttribute", "9 氣動閥", None))
        self.comboBox_valve_type.setItemText(10, _translate("ValveAttribute", "A 水力自動閥", None))
        self.comboBox_valve_type.setItemText(11, _translate("ValveAttribute", "B 逆止閥", None))
        self.comboBox_valve_type.setItemText(12, _translate("ValveAttribute", "C 排氣閥", None))
        self.comboBox_valve_type.setItemText(13, _translate("ValveAttribute", "D 減壓、持壓閥", None))
        self.comboBox_valve_type.setItemText(14, _translate("ValveAttribute", "E 洩壓閥", None))
        self.label_bury_loc.setText(_translate("ValveAttribute", "埋設位置", None))
        self.label_valve_size.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">口徑</span></p></body></html>", None))
        self.label_bury_depth.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">埋設深度</span></p></body></html>", None))
        self.label_angle.setText(_translate("ValveAttribute", "旋轉角度", None))
        self.label_const_unit.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">監造單位</span></p></body></html>", None))
        self.label_remark.setText(_translate("ValveAttribute", "註記說明", None))
        self.label_valve_mode.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">測量註記</span></p></body></html>", None))
        self.label_bury_date.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">埋設日期</span></p></body></html>", None))
        self.label_unific_id.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">識別碼</span></p></body></html>", None))
        self.pushButtonOK.setText(_translate("ValveAttribute", "儲存", None))
        self.label_coord_97z.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">地盤高程</span></p></body></html>", None))
        self.label_coord_97y.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#aa0000;\">位置Ｙ坐標(TWD97)</span></p></body></html>", None))
        self.label_coord_67x.setText(_translate("ValveAttribute", "位置Ｘ坐標(TWD67)", None))
        self.label_valve_sw.setText(_translate("ValveAttribute", "開關轉向", None))
        self.label_maint_date.setText(_translate("ValveAttribute", "<html><head/><body><p><span style=\" color:#000000;\">養護檢查</span></p><p><span style=\" color:#000000;\">日期及記錄</span></p></body></html>", None))
        self.btUID.setText(_translate("ValveAttribute", "填入識別碼", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ValveAttribute", "屬性", None))
        self.groupBox.setTitle(_translate("ValveAttribute", "位置描述", None))
        self.lbl_pin1.setText(_translate("ValveAttribute", "第一支點      距【】【】公尺", None))
        self.lbl_pin2.setText(_translate("ValveAttribute", "第二支點      距【】【】公尺", None))
        self.lbl_pin3.setText(_translate("ValveAttribute", "第三支點      距【】【】公尺", None))
        self.groupBox_2.setTitle(_translate("ValveAttribute", "第一支點", None))
        self.label_9.setText(_translate("ValveAttribute", "距", None))
        self.cbP1pos.setItemText(1, _translate("ValveAttribute", "電力桿", None))
        self.cbP1pos.setItemText(2, _translate("ValveAttribute", "電信桿", None))
        self.cbP1pos.setItemText(3, _translate("ValveAttribute", "電力人孔", None))
        self.cbP1pos.setItemText(4, _translate("ValveAttribute", "電信人孔", None))
        self.cbP1pos.setItemText(5, _translate("ValveAttribute", "電信箱座", None))
        self.cbP1pos.setItemText(6, _translate("ValveAttribute", "路燈", None))
        self.cbP1pos.setItemText(7, _translate("ValveAttribute", "交通號誌", None))
        self.cbP1pos.setItemText(8, _translate("ValveAttribute", "門柱", None))
        self.cbP1pos.setItemText(9, _translate("ValveAttribute", "屋角", None))
        self.cbP1pos.setItemText(10, _translate("ValveAttribute", "建物", None))
        self.cbP1pos.setItemText(11, _translate("ValveAttribute", "三角點", None))
        self.cbP1pos.setItemText(12, _translate("ValveAttribute", "水準點", None))
        self.cbP1pos.setItemText(13, _translate("ValveAttribute", "變電箱座", None))
        self.cbP1pos.setItemText(14, _translate("ValveAttribute", "變壓箱座", None))
        self.cbP1pos.setItemText(15, _translate("ValveAttribute", "安全島", None))
        self.cbP1pos.setItemText(16, _translate("ValveAttribute", "水池", None))
        self.cbP1pos.setItemText(17, _translate("ValveAttribute", "板牆", None))
        self.cbP1pos.setItemText(18, _translate("ValveAttribute", "圍牆", None))
        self.cbP1pos.setItemText(19, _translate("ValveAttribute", "路邊", None))
        self.cbP1pos.setItemText(20, _translate("ValveAttribute", "鐵絲網", None))
        self.cbP1pos.setItemText(21, _translate("ValveAttribute", "路標", None))
        self.cbP1pos.setItemText(22, _translate("ValveAttribute", "其他", None))
        self.label_8.setText(_translate("ValveAttribute", "公尺", None))
        self.label_16.setText(_translate("ValveAttribute", "X", None))
        self.label_17.setText(_translate("ValveAttribute", "Y", None))
        self.btP1xy.setText(_translate("ValveAttribute", "選取支點位置", None))
        self.groupBox_3.setTitle(_translate("ValveAttribute", "第二支點", None))
        self.label_18.setText(_translate("ValveAttribute", "距", None))
        self.cbP2pos.setItemText(1, _translate("ValveAttribute", "電力桿", None))
        self.cbP2pos.setItemText(2, _translate("ValveAttribute", "電信桿", None))
        self.cbP2pos.setItemText(3, _translate("ValveAttribute", "電力人孔", None))
        self.cbP2pos.setItemText(4, _translate("ValveAttribute", "電信人孔", None))
        self.cbP2pos.setItemText(5, _translate("ValveAttribute", "電信箱座", None))
        self.cbP2pos.setItemText(6, _translate("ValveAttribute", "路燈", None))
        self.cbP2pos.setItemText(7, _translate("ValveAttribute", "交通號誌", None))
        self.cbP2pos.setItemText(8, _translate("ValveAttribute", "門柱", None))
        self.cbP2pos.setItemText(9, _translate("ValveAttribute", "屋角", None))
        self.cbP2pos.setItemText(10, _translate("ValveAttribute", "建物", None))
        self.cbP2pos.setItemText(11, _translate("ValveAttribute", "三角點", None))
        self.cbP2pos.setItemText(12, _translate("ValveAttribute", "水準點", None))
        self.cbP2pos.setItemText(13, _translate("ValveAttribute", "變電箱座", None))
        self.cbP2pos.setItemText(14, _translate("ValveAttribute", "變壓箱座", None))
        self.cbP2pos.setItemText(15, _translate("ValveAttribute", "安全島", None))
        self.cbP2pos.setItemText(16, _translate("ValveAttribute", "水池", None))
        self.cbP2pos.setItemText(17, _translate("ValveAttribute", "板牆", None))
        self.cbP2pos.setItemText(18, _translate("ValveAttribute", "圍牆", None))
        self.cbP2pos.setItemText(19, _translate("ValveAttribute", "路邊", None))
        self.cbP2pos.setItemText(20, _translate("ValveAttribute", "鐵絲網", None))
        self.cbP2pos.setItemText(21, _translate("ValveAttribute", "路標", None))
        self.cbP2pos.setItemText(22, _translate("ValveAttribute", "其他", None))
        self.label_19.setText(_translate("ValveAttribute", "公尺", None))
        self.label_20.setText(_translate("ValveAttribute", "X", None))
        self.label_21.setText(_translate("ValveAttribute", "Y", None))
        self.btP2xy.setText(_translate("ValveAttribute", "選取支點位置", None))
        self.groupBox_4.setTitle(_translate("ValveAttribute", "第三支點", None))
        self.label_22.setText(_translate("ValveAttribute", "距", None))
        self.cbP3pos.setItemText(1, _translate("ValveAttribute", "電力桿", None))
        self.cbP3pos.setItemText(2, _translate("ValveAttribute", "電信桿", None))
        self.cbP3pos.setItemText(3, _translate("ValveAttribute", "電力人孔", None))
        self.cbP3pos.setItemText(4, _translate("ValveAttribute", "電信人孔", None))
        self.cbP3pos.setItemText(5, _translate("ValveAttribute", "電信箱座", None))
        self.cbP3pos.setItemText(6, _translate("ValveAttribute", "路燈", None))
        self.cbP3pos.setItemText(7, _translate("ValveAttribute", "交通號誌", None))
        self.cbP3pos.setItemText(8, _translate("ValveAttribute", "門柱", None))
        self.cbP3pos.setItemText(9, _translate("ValveAttribute", "屋角", None))
        self.cbP3pos.setItemText(10, _translate("ValveAttribute", "建物", None))
        self.cbP3pos.setItemText(11, _translate("ValveAttribute", "三角點", None))
        self.cbP3pos.setItemText(12, _translate("ValveAttribute", "水準點", None))
        self.cbP3pos.setItemText(13, _translate("ValveAttribute", "變電箱座", None))
        self.cbP3pos.setItemText(14, _translate("ValveAttribute", "變壓箱座", None))
        self.cbP3pos.setItemText(15, _translate("ValveAttribute", "安全島", None))
        self.cbP3pos.setItemText(16, _translate("ValveAttribute", "水池", None))
        self.cbP3pos.setItemText(17, _translate("ValveAttribute", "板牆", None))
        self.cbP3pos.setItemText(18, _translate("ValveAttribute", "圍牆", None))
        self.cbP3pos.setItemText(19, _translate("ValveAttribute", "路邊", None))
        self.cbP3pos.setItemText(20, _translate("ValveAttribute", "鐵絲網", None))
        self.cbP3pos.setItemText(21, _translate("ValveAttribute", "路標", None))
        self.cbP3pos.setItemText(22, _translate("ValveAttribute", "其他", None))
        self.label_23.setText(_translate("ValveAttribute", "公尺", None))
        self.label_24.setText(_translate("ValveAttribute", "X", None))
        self.label_25.setText(_translate("ValveAttribute", "Y", None))
        self.btP3xy.setText(_translate("ValveAttribute", "選取支點位置", None))
        self.pushButtonOK_valve_pin.setText(_translate("ValveAttribute", "儲存", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ValveAttribute", "三支距", None))
        self.btPrephoto.setText(_translate("ValveAttribute", "上一張", None))
        self.btNextphoto.setText(_translate("ValveAttribute", "下一張", None))
        self.btOpenphoto.setText(_translate("ValveAttribute", "開啟照片", None))
        self.lbl_photoname.setText(_translate("ValveAttribute", "檔名：", None))
        self.pushButton_open_folder.setText(_translate("ValveAttribute", "開啟存檔資料夾", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ValveAttribute", "現況圖", None))
        self.pushButton_select_folder.setText(_translate("ValveAttribute", "選擇資料匣", None))
        self.pushButton_save.setText(_translate("ValveAttribute", "儲存照片", None))
        self.ckPosmap.setText(_translate("ValveAttribute", "位置圖", None))
        self.ckMemo.setText(_translate("ValveAttribute", "記錄卡", None))
        self.btExport.setText(_translate("ValveAttribute", "轉出圖卡", None))
        self.pushButtonCancel.setText(_translate("ValveAttribute", "取消", None))

